### ISSUE TITLE
[Bug] Cannot proceed past final introduction page/tile

### ISSUE THREAD

**Issue by daveoftheday** [XRPL-Labs/XUMM-Issue-Tracker#100]
Bug Report:

XUMM App downloaded from google play store app. XUMM installs no problem. upon opening you are given 4 tile introduction pages. when the last page is reached, the "skip" button does not turn green to be able to continue using the app. Works fine on my girlfriends android phone.

* Manufacturer: Google
* Model: Pixel 3a
* OS version: Android 10
* OS Build: QQ2A.200305.002

![IMG_20200401_003354_01](https://user-images.githubusercontent.com/62979102/78100440-c4b83180-73b2-11ea-9603-cafb37c18b2a.jpg)

**Comment by WietseWind** [comment]
Thank you @daveoftheday - Really appreciate you reporting this!
We are aware (https://github.com/XRPL-Labs/XUMM-Issue-Tracker/issues/60) and we're fixing it  ASAP for a new Beta release :)
