### ISSUE TITLE
[Bug] showing wrong currency unit in Events (SOLO transaction)

### ISSUE THREAD

**Issue by xrpbird** [XRPL-Labs/XUMM-Issue-Tracker#105]
iPhone XS Max
iOS 13.4
Dark Mode ON
XUMM Version 0.2.4.1

Under "Events" it shows not the correct unit behind a SOLO transaction.
Screenshot: https://imgur.com/V0X1PTG

Sender: SOLO Wallet App

**Comment by WietseWind** [comment]
Thank you, we should to the IOU to Text conversion there as well. Appreciate it @xrpbird
