### ISSUE TITLE
[Bug] Font size goes nuts on rare occasions

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#120]
Android. On rare occasions (happened multiple times) the font size went crazy. Force quitting the app and starting it again solves it.
(Twitter: @SASchofield52)

![image](https://user-images.githubusercontent.com/4756161/78460832-8aa5a300-76c4-11ea-8b71-393c8ffdb0cb.png)
![image](https://user-images.githubusercontent.com/4756161/78460834-9002ed80-76c4-11ea-8dcb-638c9bf66265.png)
![image](https://user-images.githubusercontent.com/4756161/78460833-8e392a00-76c4-11ea-947f-2d03c26a85a4.png)

**Comment by Pucksterpete** [comment]
I like the LARGE font size :)

**Comment by N3TC4T** [comment]
`Samsung Galaxy Note 10+ 5G, Android ver: 10`

Just for the note

**Comment by N3TC4T** [comment]
Fixed in https://github.com/XRPL-Labs/XUMM-App/commit/6011f7c05f6a8c20df53dad11dcbc4eb0b86e471
