### ISSUE TITLE
[Improvement] Events list: match address (and tag, or if no match: without tag)

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#131]
If the event list shows a transaction from/to an address that is in the address book, show that name in the list view instead of the r address.
Local address book prevails above lookup service, so no lookup is required if already matched @ address book.

**Comment by WietseWind** [comment]
https://app.intercom.com/a/apps/nq9rb5du/inbox/inbox/all/conversations/26641929917

**Comment by N3TC4T** [comment]
this is already happening in the latest version ,but if you open the events list and then add the contact and back to the list, the old value would be there, as the events screen contain a big list, for performance we don't re-render items in the list.

**Comment by WietseWind** [comment]
@N3TC4T That may be it. I'll contact the user :) Thanks!
