### ISSUE TITLE
[Improvement] Conditions for IOU liquidity warnign

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#133]
When reviewing a sign request, there's a warning if there is not enough liquidity.

That liquidity is **only relevant when the IOU has to be converted**. So: if the sending amount (sender) IOU is the same as the amount to be delivered (recipient has a trust line for that issuer + IOU) there is no conversion happening so liquidity is irrelevant. 

This message should only be displayed if a conversion will happen (sender sends something that the recipient doesn't have a trust line setup for, so it'll be DEX converted).

![image](https://user-images.githubusercontent.com/4756161/79370382-d83acf00-7f52-11ea-937f-6622fcffb5d9.png)

**Comment by N3TC4T** [comment]
The condition apply for having the same trustline and the exchange rate won't be shown to the user but if the trustline doesn't have enough balance to covert the request amount it's will be use XRP again

**Comment by WietseWind** [comment]
@WietseWind wouldn't then the screen show that it's being handled as XRP because there's insufficient balance in the requested currency?
@nixer89 Can it be the case that there was insufficient balance?

**Comment by nixer89** [comment]
Of course it was insufficient balance because I was in the process to issue an IOU (which never existed before) to an account 😅

The trust line on side of the issuer account now says -50 XXX and the trust line on the recipient says +50 XXX. As it should be :)

Balances of the trustline before the transactions were 0 on both sides (new trust line).

Anyway, the message is really confusing in the case of issuing tokens to an account. I have some people testing this function already and they were all asking me about the message.

**Comment by WietseWind** [comment]
@nixer89 Ah this screenshot is from the perspective of the issuer sending?

@N3TC4T So: if sending account = issuer & sending same currency: no fallback to XRP and balance < 0 = still OK

**Comment by nixer89** [comment]
Yes, this was a payment from the issuer to the iou recipient.

You can test it on https://test.xumm.community/easy-iou 😇

**Comment by WietseWind** [comment]
@nixer89 Got it, thanks. I know enough :)
@N3TC4T:
If the account is the ISSUER, we should not show the balances per line but overall, "obligations", as one big negative amount. Currency: as is (with HEX name logic) and issuer: not the destination line account but literally: `Issued`.
When tapped: remove button not present, send button active.

This is easy to detect: if the `balance` is negative, or `limit` is zero and `limit_peer` > 0.

The balance should not be the addition of all lines with the issuances (as it can be paged), the easier way would be to call the `gateway_balances` method:
```
{
  "command": "gateway_balances",
  "account": "r..."
}
```

Response:
```
{
  account: r...
  ledger_current_index: 55196767
  obligations: {
    EUR: 120.689342403628
  }
```

https://cg4ksbg.dlvr.cloud/pasted_1.png
The self issued currency should be available at Send as well (sending own IOU to others), balance is allowed to be below zero to send as it's self issued. Just like normal Send transactions: no DEX conversion required if IOU to IOU.

**Comment by WietseWind** [comment]
Reopened, @nixer89 can you elaborate? Still a liquidity warning for self issued tokens?

**Comment by nixer89** [comment]
Yes, when viewing a sign request for a payment of an IOU from an account with a negative balance on the trust line (usually the account which issues the token) to another account, the liquidity warning is still shown:

![IMG_1051](https://user-images.githubusercontent.com/25486793/82992724-d5c29f00-9fff-11ea-8b00-3aec91b47dd7.PNG)

**Comment by N3TC4T** [comment]
Interesting, should have been fixed with this commit 

https://github.com/XRPL-Labs/XUMM-App/pull/30/commits/35dedf56307d351260267e415e93302d4d776cdf
