### ISSUE TITLE
[Change] Revert node (s2 to xrpl.ws, or testnet) after new cold start

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#134]
When XUMM offers to select another node (when the configured node can't be reached a few times in a row), do not change the new node in a persisting manner.

So let's say: connected to xrpl.ws, down, switching to S2 (app offers to switch) » so when connected to S2, and a full close and cold start of the app happens again, go back to default (xrpl.ws or testnet.xrpl-labs.com depending on the active net)

**Comment by nixer89** [comment]
Uhm, tbh, don't like that. I would like to have the option to use another node persistently.

Request for change:

only on connection issues, change temporary  to another node and on next restart go back to the node which is originally selected in the settings (xrpl.ws or ripple)

**Comment by WietseWind** [comment]
@nixer89 Updated the issue, thanks. I meant only for offered switching when the primary selected node is down and the user gets the offer to switch and accepts.

**Comment by WietseWind** [comment]
@thisistriss
