### ISSUE TITLE
[Improvement] Only allow OS native keyboard for sensitive data inputs

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#135]
Only allow the OS native keyboard for inputs with sensitive data such as secret numbers, family seeds or mnemonics.

There is a risk for third party keyboards to keylog the inputs and send it somewhere/store it somewhere (such as for "improving their service" or their auto correction feature).

When entering sensitive data, it should only be allowed to do so by the default, OS native keyboard and not through 3rd party keyboards.

**Comment by WietseWind** [comment]
@nixer89 Thanks, we're aware of this :) 

@N3TC4T I believe you implemented this recently, right? For the new beta release? For passphrase, mnemonic, family seed, ..?
