### ISSUE TITLE
[Improvement] Add XRPL node & handle offline / can't connect

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#139]
# 1. Add a node
- wss://xrpl.ws
- wss://s2.ripple.com

I'd like to add a node endpoint `wss://xrpl.link` between them: a fallback entry point in case Cloudflare Argo Tunnels go down (like happened a few days ago):

- wss://xrpl.ws
- **`wss://xrpl.link`**
- wss://s2.ripple.com

### Please note: this hostname should be added in the native code for WS endpoint filtering too.

# 2. Auto new node selection
If XUMM detects the selected node cannot be reached for X times, **automatically** try the next node, and the next, etc. If a connection can be made this way, **revert to the originally selected node** when the app starts again.

# 3. Allow XUMM open & inform user if all nodes fail
If no connection can be made (so the user is likely cutoff from the internet) show something like this:
![image](https://user-images.githubusercontent.com/4756161/79566928-a0976880-80b3-11ea-8d2c-74369af0e533.png)

---
This replaces #138 and #134

**Comment by alloyxrp** [comment]
Consider adding truth IP addresses. From different providers. Such as 1.1.1.1 and 8..8.8.8 . This will allow the app to identify total loss of connectivity or partial.
