### ISSUE TITLE
[Feature] Payload options: forceAccount, forceSequence, immutable

### ISSUE THREAD

**Issue by patriksletmo** [XRPL-Labs/XUMM-Issue-Tracker#144]
It is currently up to the user to select which account they want to sign a transaction for, since the tx.Account field in txjson is ignored by design. This is sub-optimal for some use cases, such as when an integration prepares a transaction based on the details of a specific account.

It would be nice to have the ability of specifying that a specific account should be used. Developers could for example enable this functionality using an optional flag in the payload options, such as `forcedAccount: true`.

(From #145 (merged here)):
### While at it: `immutable: true` option to force the transaction to be signed **AS IS**, without the XUMM flow changing eg. fee / account / sequence / ...

The lack of this functionality also makes some transactions, such as OfferCancel, somewhat dangerous. OfferCreate specifies the offer to cancel using an account specific ID, and if the user changes which account to use this ID will either point to another offer or to nothing at all.

The proposed functionality must not conflict with the possibility to sign a transaction on behalf of another account. Given two accounts A and B, where B is a regular key for A, it should be possible to force xumm to sign a transaction for account A by specifying it in the tx.Account field. However, the user should still be able to sign with account B (either if the master key of A is disabled, or if A has been added as a read-only account, see #80).

Care must also be taken so that an error is presented if the specified tx.Account is not added to xumm. » See Note:

### Node by @WietseWind:
The warning about the sending account not being present can be omitted if that account DOES have a Account config (reg key) pointing to an account that is present (read write) in XUMM.

**Comment by RareData** [comment]
This feature is needed to completely integrate Xumm with XRP Toolkit and highly desired to rule out potential issues between a client and Xumm. It would significantly improve immutability and make it possible to verify correctness in both ends.

**Comment by WietseWind** [comment]
Thanks @patriksletmo & @RareData - I understand the reason for adding this. We will include this in one of coming Beta releases :)

**Comment by WietseWind** [comment]
![image](https://user-images.githubusercontent.com/4756161/81280150-625ceb80-9058-11ea-8656-173e44129c9d.png)
![image](https://user-images.githubusercontent.com/4756161/81280159-65f07280-9058-11ea-9a1b-5044916cd171.png)

**Comment by KoenPaas** [comment]
Merge issue into extended proposal: #384
