### ISSUE TITLE
[Feature] Support for preventing modifications of the signed transaction

### ISSUE THREAD

**Issue by patriksletmo** [XRPL-Labs/XUMM-Issue-Tracker#145]
For some use-cases, such as multi-signing or when an integration only desires a transaction to be signed as-is, it is important that the transaction content is not modified. I am not entirely certain how it works when multi-signing, but it is not possible to prevent editing of every transaction with the current API. The current behavior allows users to edit fields such as the payment amount or memos.

To support this use-case, an optional flag to the payload options could be added. A flag such as `forceTxAsIs: true` could be specified to prevent xumm from making any modifications to the supplied txjson.

I am unsure how clever fields such as `maxLedgerSequence` should be handled, but I _think_ that it could be possible to keep that functionality as-is. The field `Sequence` should, however, always be preserved since the integration may wish to pre-sign a transaction. This is of course open for discussion, but since there are some use-cases for pre-signed transactions, such as self-custodial stop orders, I think that such functionality is motivated.

**Comment by RareData** [comment]
I agree with @patriksletmo. However, I think "forceTxAsIs: true" is error prone due to its complex casing, how about `immutable: true`? If a prepared TX is flagged as immutable, no changes should be allowed at all.

**Comment by patriksletmo** [comment]
I support the `immutable: true` naming and agree with the issues of my initial proposal.

**Comment by WietseWind** [comment]
I understand the use case, but I just checked, and for Requests (with an amount filled) nothing can be changed except for the signing account, which will be fixed if we (and we will) implement #144 

Maybe there's some confusion with the (manual) "Send" flow, where a memo can be added indeed? Requests don't allow users to edit fields (except Amount, if the amount isn't filled in the request and the request is a Payment)

**Comment by WietseWind** [comment]
@RareData +1 for the `immutable` property.

**Comment by patriksletmo** [comment]
It appears you're right, @WietseWind. As for the `Sequence` field, is it possible to prevent it from being auto-filled?

**Comment by WietseWind** [comment]
Great @patriksletmo - How about adding another meta option for that, just like `forcedAccount: true` in #144: `forcedSequence: true`?

**Comment by patriksletmo** [comment]
Sounds very reasonable!
