### ISSUE TITLE
[Feature] Support signing on behalf of an account that has not been added in the app

### ISSUE THREAD

**Issue by patriksletmo** [XRPL-Labs/XUMM-Issue-Tracker#146]
As far as I understand, the current application behavior does not allow users to sign transactions on behalf of an account that they have not added as read/write already. The issue #80 improves this situation somewhat by allowing users to sign transactions on behalf of accounts that has been added as read-only provided that the regular key for that account is added as a read/write account.

With the proposal of issue #144, it would be useful to support use-cases where the provided tx.Account has not been added to the xumm app at all, but rather that only their regular key has. This would make it easier for users since they would only have to add their read-only account in the application containing the xumm integration instead of in both applications.

While it might be argued that users who regularly sign on behalf of another account should want to observe that account often enough to warrant adding it in the xumm app, this might not be the case for everyone. Users that do this more rarely could instead find the requirement annoying. By allowing the user to sign the transaction regardless, applications that integrate xumm does not have to handle the edge-case of a missing account in xumm, and can provide a better experience to the user.

**Comment by RareData** [comment]
Fully agree. For maximum usability and interoperability, there should be no strict requirement to add all accounts to Xumm, it should be enough to have the signing account added in Xumm. This would also improve privacy and separation of concerns.

**Comment by WietseWind** [comment]
Completely agree. I will merge this with #80
