### ISSUE TITLE
[Feature] Opt-in support for specifying arbitrary transaction fees

### ISSUE THREAD

**Issue by patriksletmo** [XRPL-Labs/XUMM-Issue-Tracker#147]
The specified transaction fee is currently modified if it is below the calculated minimum fee threshold, see [this](https://github.com/XRPL-Labs/XUMM-App/blob/10df2e5b22fdba4d90b5d4d3273df5be1ac28dd2/src/screens/Modal/ReviewTransaction/Templates/Global.tsx#L41). It would be nice to have the option of overriding this behavior to ensure that the submitted transaction is not modified before it's signed.

I know that there is often a good reason to set a minimum fee amount, but I think that this responsibility could be on the transaction submitter as well, given that the integration opts in to this behavior. Also, the minimum fee that is enforced in XUMM is the ledger base fee [plus a cushion of 20%](https://github.com/WietseWind/rippled-ws-client/blob/8de960538a4539c77586ff03ff333c3deaf8a3cb/src/index.js#L133). It seems logical to recommend this practice, but not to enforce it.

**Comment by patriksletmo** [comment]
Also, the current implementation does not seem to support [free SetRegularKey transactions](https://xrpl.org/transaction-cost.html#key-reset-transaction).

**Comment by WietseWind** [comment]
@N3TC4T Let's do this:
1. `Send a SetRegularKey transaction with a transaction cost of 0, as long as the account's lsfPasswordSpent flag is disabled. This transaction must be signed by the account's master key pair. Sending this transaction enables the lsfPasswordSpent flag.`
2. If `Fee` is set on the transaction template from the backend: use `Fee` **

** Only respect user defined Fee if max 10k drops (0.1 XRP) to prevent expensive mistakes, UNLESS it is a AccountDelete transaction: then use a fee of 5000k (5 XRP) drops. If the Fee field is not defined on the transaction template, perform the existing calculation.

**Comment by WietseWind** [comment]
The programmed (api, Payload) change is outlined above. For the user interface side:

As is, but at settings - advanced: "Allow custom fee"
If enabled, the fee is still automatically determined, but if **no override by the Payload**, and if **not** forced by TX type (existing code), a pencil icon is enabled so users can modify the fee, no value higher than 1 XRP accepted.

**Comment by N3TC4T** [comment]
This will already be fixed by #144 (immutable transaction signing), and the 12 drops for setting the first Regular Key: we'll leave that as is, at least for now (as discussed with @WietseWind)

**Comment by N3TC4T** [comment]
Closing this issue as with the new fee calculation, we do not touch the fee if it's already set in the payload.
