### ISSUE TITLE
[Improvement] Always show biometric authentication option under settings

### ISSUE THREAD

**Issue by RareData** [XRPL-Labs/XUMM-Issue-Tracker#153]
I tried to enable biometric authentication by navigating to Settings > Security, but could only see PIN and auto lock settings. Since I hadn't added any fingerprint to Android, I took a guess that I might need to add one through the regular phone settings before it'd show up. Once I had added a fingerprint through the phone's settings, Xumm started showing "Biometric Authentication" as an option. 

I think it'd be beneficial if Xumm would always show "Biometric Authentication" as an option, but if no fingerprint has been added, then suggest that the user adds one. Perhaps also link to the related phone settings.

**Comment by WietseWind** [comment]
Good one. We should just show it, disabled, with a link to a modal informing users to enable whatever is on their hardware+OS instead of hiding it entirely 👍

**Comment by N3TC4T** [comment]
`Biometric sign in (fingerprint or Face ID) is unavailable. If your device supports biometric sign in, please configure it first (OS settings).`
