### ISSUE TITLE
[Bug] TrustSet transactions always say "Add a currency (Trust line)"

### ISSUE THREAD

**Issue by RareData** [XRPL-Labs/XUMM-Issue-Tracker#154]
When removing a trust line using the XRP Toolkit v2, a TrustSet transaction is prepared for the user with a limit amount of zero (and whatever else is needed to put the trust line in its default state). No matter what TrustSet transaction I send, Xumm always says "Add a currency (Trust line)" even for limit amount zero. I expect Xumm to say something along the lines of "Remove a currency (Trust line)" in this case.

**Comment by WietseWind** [comment]
So: LimitAmount = zero = title "Remove a currency" 👍  Thanks!
