### ISSUE TITLE
[Bug] QR scan button for family seed overlays text

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#156]
**Describe the bug**
The new scan button for the family seed overlays some text from the box (see screenshot)

**To Reproduce**
1. Add new full access account
2. Choose Family Seed
3. See error

**Expected behavior**
Button does not overlay text

**Screenshots**
![IMG_0837](https://user-images.githubusercontent.com/25486793/81036096-0fd7cf80-8e9e-11ea-9cb1-e529e1fbf804.PNG)

Does not look good as well when a family seed was scanned:
![IMG_0840](https://user-images.githubusercontent.com/25486793/81036989-6abef600-8ea1-11ea-8b5b-e6b8df36725c.PNG)

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 0.4.0.3

What device are you running XUMM on?

* Manufacturer: Apple
* Model: iPhone SE
* OS version: 13.x
* Platforms
  * [x] iOS
  * [ ] Android

**Comment by WietseWind** [comment]
@thisistriss @N3TC4T Smaller screen size, maybe we can just use more width if this is the case? As there's quite some padding on the x axis?
