### ISSUE TITLE
[Bug] Address book: adding contact name hides input field

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#157]
**Describe the bug**
When adding a new contact and trying to write in the name, the field for the contact name is being hidden and cannot be seen through scrolling (scrolling not available on that page)

(maybe it is due to the custom keyboard?)

**To Reproduce**
1. Address book
2. Add new contact
3. Select field for contact name

**Expected behavior**
Whether this page should be scrollable so I can see what I actually type or even better, the contact name field stays visible :)

**Screenshots**
(I made a screencap, see mattermost beta channel)

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: [0.4.0.3]

What device are you running XUMM on?

* Manufacturer: [Apple]
* Model: [iPhone SE]
* OS version: [13.x]
* Platforms
  * [x] iOS
  * [ ] Android

### Additional context
Attach crash logs if available. Please ensure that these files do not contain any personal information.

**Comment by WietseWind** [comment]
https://n241ufr.dlvr.cloud/LVEJ2179.MP4
