### ISSUE TITLE
[Bug] Open transaction details in main/testnet explorer, Settings: select explorer

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#158]
**Describe the bug**
When XUMM is connected to a test node, the transaction hash is opened in safari on livenet. xrpl.org

**To Reproduce**
0. Connect XUMM to a test node 
1. Go to 'Events'
2. Click on a transaction
3. Click the three little dots top right
4. Select open in Browser

**Expected behavior**
When connected to a test node, the transaction hash should be opened through testnet.xrpl.org because the transaction can not be found on the live net.

**Screenshots**
![FADE1620-6394-4F5B-B4E8-173D63FAF553](https://user-images.githubusercontent.com/25486793/81099450-397b1000-8f0b-11ea-9063-d5c79b2b9b40.png)
![3420F53B-F4FF-4589-89CA-DC3BE96B1789](https://user-images.githubusercontent.com/25486793/81099455-3bdd6a00-8f0b-11ea-9b3a-87e61bfb4618.png)

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 0.4.0.3

What device are you running XUMM on?

* Manufacturer: 
* Model: [FILL THIS OUT]
* OS version: [FILL THIS OUT]
* Platforms
  * [x] iOS
  * [ ] Android

### Additional context
Attach crash logs if available. Please ensure that these files do not contain any personal information.

**Comment by WietseWind** [comment]
Great suggestion. 

Let's combine this with a settings panel where one can select their preferred explorer for mainnet vs livenet:

Mainnet:
https://bithomp.com/explorer/{hash}
https://xrpscan.com/tx/{hash}
https://livenet.xrpl.org/transactions/{hash}

Testnet:
https://test.bithomp.com/explorer/{hash}
https://testnet.xrpl.org/transactions/{hash}

**Comment by nixer89** [comment]
Can we please extend the list by xrp1ntel? 😇
![0A970D7E-8E92-4854-AA27-3411A6A88700](https://user-images.githubusercontent.com/25486793/81136372-ae763600-8f5b-11ea-9946-1e10e3a0f36a.jpeg)

**Comment by WietseWind** [comment]
Added: XRPlorer.
