### ISSUE TITLE
[Bug] XUMM app does not load Trust Lines when currency code has special characters

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#159]
**Describe the bug**
When an XRPL account has a Trust Line with the currency code (as example) "%^&", the XUMM app does not load the trust lines and says "no currencies available".
Also the "Events" screen keeps crashing / stays white.

**To Reproduce**
1. Create TrustLine with currency code "%^&"
2. Open/Reopen app
3. Trust Lines (all) are not loaded and Events screen stays white / is crashing

**Expected behavior**
All TrustLines will be shown

**Screenshots**
Screenshots from App:

![IMG_0875](https://user-images.githubusercontent.com/25486793/81273146-c24e9480-904e-11ea-8eff-41f3cf301f82.PNG)
![IMG_0876](https://user-images.githubusercontent.com/25486793/81273149-c37fc180-904e-11ea-8877-27768a235892.PNG)

Proof that TrustLines exists:
![grafik](https://user-images.githubusercontent.com/25486793/81273207-d72b2800-904e-11ea-8665-7d97808537de.png)

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 0.4.1.1

What device are you running XUMM on?

* Manufacturer: Apple
* Model: iPhone SE
* OS version: 13.x
* Platforms
  * [x] iOS
  * [ ] Android

### Additional context
SessionLog has been sent to XUMM support mail address

**Comment by WietseWind** [comment]
Duplicate to #162, closing this one.
