### ISSUE TITLE
[Improvement] Add AccountDelete support + custom tx messages 

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#163]
Error (AccountDelete but is more generic I think?) » See Nixer @ XUMM Beta

1. This is at testnet, AccountDelete should work
2. If an error happens: shouldn't the alert show the error instead of the error-about-an-error?

https://k9l2vq6.dlvr.cloud/pasted_2.png

### General message:
> DANGER! This is an Account Delete transaction. When signing your account will be deleted, and all your remaining funds (except for the last 5 reserved XRP, as the fee on the XRP ledger for deleting an account is 5 XRP) will be sent to the configured destination.
> Please check the destination twice, and ONLY continue if you ACTUALLY want to delete your account on the XRP ledger.

### Message when account objects are still present (and signing is not allowed)
> You cannot delete this account, as your account contains specific XRP ledger objects, like other currencies, Decentralized Exchange offers, Escrows (as a creator or beneficiary)

# Validation
AccountDelete Validation:
The 5XRP AccountDelete fee [will *ALSO* be charged](https://xrpcharts.ripple.com/#/transactions/10E8CD4120EC9398A1C40CA2C26A066B5AA3D0C8A4695FD1F091E608B0D28338) if the delete DOESN'T happen because of validation.

This is horrible if people eg. have obligations / IOU's (Trust Lines), escrows, etc. and try to delete anyway: 5XRP gone, nothing executed.

So before allowing someone to sign a AccountDelete transaction, we should do an "account_objects" transaction to see if it's empty: 
Not empty:
```
{
  "command": "account_objects",
  "account": "rPdvC6ccq8hCdPKSPJkPmyZ4Mi1oG2FFkT"
}
```

Empty:

```
{
  "command": "account_objects",
  "account": "rwiEtSeCWbHFfagJ84twaKQk9SPuh6R6Wv"
}
```

---

Add DeletableAccounts payload confirmation screen, highlighting the remaining funds destination account (+ resolve) 
```
    "Destination": "rPT1Sjq2YGrBMTttX4GZHjKu9dyfzbpAYe",
    "DestinationTag": 13,
```

& BIG FAT WARNING

---

Check with https://github.com/XRPL-Labs/XUMM-Issue-Tracker/issues/170 as well

**Comment by WietseWind** [comment]
For some users this freezes the app when specific steps are taken:
https://twitter.com/___IoV___/status/1258862331280449538

@N3TC4T 
1. Sign and submit Tx: "TransactionType": "AccountDelete"
2. #Xumm -> "explain my balance"
3. application(Xumm) freezes (does not respond)

Maybe only for [me](https://twitter.com/___IoV___/status/1258862331280449538), I'm testing on a very old smartphone + LeneageOS 14.1-20190215 (Android 7.1.2)

**Comment by SASchofield** [comment]
Consider amending "General Message" to avoid confusion:
 "DANGER! This is an Account Delete transaction. Once signed, your account will be deleted. The fee is 5 XRP, with any remaining XRP sent to your configured destination."

Possibly include a note for clarity?:
"The 5 XRP 'fee' is a network requirement and isn't paid to anyone. Like the transaction fee, this XRP is simply removed from circulation... A process called 'Burning'."

**Comment by WietseWind** [comment]
@SASchofield Thank you, I like it! 
@N3TC4T Can you make that fit somehow?

**Comment by nixer89** [comment]
Hey guys,

if I may chime in...
I just saw this issue and was reading through it. Regarding:

"
You cannot delete this account, as your account contains specific XRP ledger objects, like other currencies, Decentralized Exchange offers, Escrows (as a creator or beneficiary)
"

It is actually possible to delete an account even if it has account_objects like offers.
Objects which are blocking the account deletion are:
- Escrows
- TrustLines (RippleState)
- Paychans
- Checks

(but I am not sure if one can have an offer even if there is no trust line? but who knows :) )

And also the SignerList would be populated through the account_objects method, but deletion is still possible :)

ps: there is also a limit that an account needs to be at least 256 ledgers old
(sequence + 256 < currentLedger)

and needs to have less than 1000 objects (offers?)

https://xrpl.org/accounts.html#deletion-of-accounts

**Comment by nixer89** [comment]
ps:

![grafik](https://user-images.githubusercontent.com/25486793/82417211-80c0df00-9a7b-11ea-89a3-4d1851b1ef43.png)

also important :-)
