### ISSUE TITLE
[Improvement] Add reserve/activation info on create/import unactivated account

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#167]
Add screen after account import or generation, after the `r..` address is shown, if the account *is not activated* (so new or imported unactivated one).

```
You [imported/created] a new account on the XRP ledger. The account is not activated. Account activation is a requirement on the XRP ledger. To activate, you will have to make a first deposit of at least 20 XRP. The first 20 XRP deposited into your account cannot be spent, but will be reserved to keep your account active and pay for on ledger fees.

Your reserved XRP will not show up as balance in XUMM, but you can view your reserve with the "Explain my balance" button in the home screen, above your XRP balance.
```

**Comment by WietseWind** [comment]
Reason for doing this, is:
1. People will know about the need to activate
2. People will know about a min. 20 XRP deposit
3. People will know their deposit will be visible with 20 XRP less, so they can expect this & less complaints/support.

**Comment by N3TC4T** [comment]
@thisistriss any idea for design or should I go with some default page ?

**Comment by WietseWind** [comment]
![IMG_0001](https://user-images.githubusercontent.com/4756161/87679846-f647e380-c77c-11ea-8234-53df7b24dd60.PNG)

**Comment by WietseWind** [comment]
![image](https://user-images.githubusercontent.com/4756161/87679922-124b8500-c77d-11ea-88e6-11240ba5d9a3.png)
