### ISSUE TITLE
[BUG] Switch account list doesn't scroll far enough

### ISSUE THREAD

**Issue by RareData** [XRPL-Labs/XUMM-Issue-Tracker#176]
After adding 8 accounts and trying to "Switch Account" to the eigth, the list doesn't scroll far enough, rather the eigth account is hidden out of sight. It can be briefly shown by pulling on the list's top bar, but once released it goes out of sight again. 

The "Switch Account" list must be made taller, so that the last item is visible once the list is scrolled to the bottom, without pulling on the list tab.

**Comment by WietseWind** [comment]
@RareData On what screen size / device are you? So we can simulate it on our end.

@N3TC4T [Screencap](https://mm.wietse.com/api/v4/files/ni59ypxcjpb1tn43ffan9njagh?download=1) by @RareData

**Comment by RareData** [comment]
1080 x 2160 pixels, 18:9 ratio.
Android 10.

**Comment by nixer89** [comment]
I have the same problem on my iPhone SE 😇

**Comment by WietseWind** [comment]
This just happened again to a user with a Samsung S10e with 7 accounts. He can only see 6 of them, the 7th is only briefly visible if he swipes the list up (https://app.frontapp.com/open/msg_cj0ivyd)
