### ISSUE TITLE
[Bug] Some 'special' (but valid) payloads are being rejected by the backend

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#185]
Some payloads are rejected with error code 603 "Error: Payload JSON transaction encoding error" even though the payload should be valid.

As example a payment payload for an IOU:

```{"txjson":{"TransactionType":"Payment","Destination":"rDn65vS7Hw2g4WHMTHdgbQ3HTyaqQ7ADmJ","Amount":{"currency":"4E69786572436F696E0000000000000000000000","issuer":"r3K1TgPvTPkWZR2Lhawpvv9YR7yYuqSXBp","value":"998662.999999999999999"},"Account":"r3K1TgPvTPkWZR2Lhawpvv9YR7yYuqSXBp"},"custom_meta":{"instruction":"- Issuing 998662.999999999999999 NixerCoin to: rDn65vS7Hw2g4WHMTHdgbQ3HTyaqQ7ADmJ\n\n- Please sign with the ISSUER account!"},"options":{"expire":5,"forceAccount":true},"user_token":"9b9a98a8-99e7-40e8-9c3e-02a60cdf7539"}```

Or just the TX:
```
{"TransactionType":"Payment","Destination":"rDn65vS7Hw2g4WHMTHdgbQ3HTyaqQ7ADmJ","Amount":{"currency":"4E69786572436F696E0000000000000000000000","issuer":"r3K1TgPvTPkWZR2Lhawpvv9YR7yYuqSXBp","value":"998662.999999999999999"},"Account":"r3K1TgPvTPkWZR2Lhawpvv9YR7yYuqSXBp"}
```

these cases I figured out:

value = "1.999999999999999" (15 decimal places) -> backend ACCEPTS payload
value = "998662.9999999999" (10 decimal places) -> backend ACCEPTS payload
value = "998662.99999999999" (11 decimal places) -> backend REJECTS payload

**Comment by WietseWind** [comment]
Note:
Backend reports (from ripple-keypairs): 
```998662.99999999999 is an illegal amount

Native values must be described in drops, a million of which...```

**Comment by WietseWind** [comment]
Looked into it ;) It's a warning by ripple-keypairs (under the hood):

```
Error: 998662.999999999999999 is an illegal amount Native values must be described in drops, a million of which equal one XRP. This must be an integer number, with the absolute value not exceeding 100000000000000000 IOU values must have a maximum precision of 16 significant digits. They are serialized as a canonicalised mantissa and exponent. The valid range for a mantissa is between 1000000000000000 and 9999999999999999 The exponent must be >= -96 and <= 80 Thus the largest serializable IOU value is: 999999999999999900000000000000000000000000000000000000000000000000000000000000000000000000000000 And the smallest: 0.000000000000000000000000000000000000000000000000000000000000000000000000000000001
```

Meaning the total digits used (in front of and behind the decimal sign) should not exceed 16 digits. The rejected example contains 17 ;)
