### ISSUE TITLE
[Bug] Exchange from/to "Switch" button doesn't always interact

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#190]
Samsung Galaxy S10 confirmed (had some other users with different devices). See title.

**Comment by WietseWind** [comment]
https://app.intercom.com/a/apps/nq9rb5du/inbox/inbox/all/conversations/27232337616

**Comment by N3TC4T** [comment]
https://github.com/facebook/react-native/issues/27232

This Should fix it, waiting to PR to merge.

https://github.com/facebook/react-native/pull/26374
