### ISSUE TITLE
[Feature] Support Checks

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#203]
Add screens:
- `CheckCreate` Create Check
- `CheckCancel` Cancel Check
- `CheckCash` Cash a Check

# CheckCreate https://xrpl.org/checkcreate.html

#### ❗  Currently, XUMM removes the `Destination` from a payload. 

The Destination (and tag, and other fields) should stay and be respected, just like `SendMax` should be respected and stay as is.

If `SendMax` is not specified in the payload, the user __must__ enter an amount, which then will be specified in the SendMax field. The user can use XRP here, or any IOU supported just like in a payment, where the only IOU's offered are the IOU's the Destination has a TrustLine setup for as well (so only same IOU<>same IOU or XRP<>XRP)

The screen should show the Destination (account), potentially the destination tag (uneditable, comes from the payload) and the amount(s) (or to be entered). Also, the `Expiration` field (if present) should show the datetime string in local user timezone. If not present, show: "Expire" » "Never expires" 

Note: Of course the max. amount to specify is the *spendable* amount in the account.

# CheckCash https://xrpl.org/checkcash.html

If the `Account` field for the Check is **not** present in read/write (potentially by Regular Key use) give an error message: 
> A Check can only be cashed if the Check destination account is present in XUMM in Read/Write (or regular key) mode.

Respect the CheckID and either `Amount` or `DeliverMin` field as is. If neither Amount & DeliverMin are specified, allow the user to enter the amount to cash.

The user __must__ enter an amount, which then will be specified in the DeliverMin field. The user can use XRP here, or any IOU supported just like in a payment, where the only IOU's offered are the IOU's the **Source** (as the Check Cash is from the perspective of the destination) has a TrustLine setup for as well (so only same IOU<>same IOU or XRP<>XRP)

The screen should show the source account, the destination account should be selected and unchangeable based on the present account in XUMM, and the original check (by hash) amount (or Send Max. amount) should be visible.

# CheckCancel https://xrpl.org/checkcancel.html

The source account should be auto selected based on the source Check `Account`. If not present in XUMM:
- If expired (Expire, ripple datetime in the past) Any read/write account can be selected
- If not expired, or no Expire field (and escrow source account not in XUMM): error: "A (non expired) check can only be cancelled by the account that created it."

Show original Check Destination, possibly Destination Tag, amount (based on SendMax or Amount).

**Comment by N3TC4T** [comment]
Detail pages should show the properties of the check (in case of cancel or cash: referring to (getting) the original check by hash and getting the details there)

Event list should show the amount in light grey (as it's not a transaction yet, it's pending, awaiting claim), underline should show destination (resolved name or truncated account)

**Comment by N3TC4T** [comment]
About CheckCash: `and the original check (by hash) amount (or Send Max. amount) should be visible.`

There is no any efficient way to get Check object or the creator account for check, by Check ID as it's calculated with this subjects:

```
The ID of a Check object is the SHA-512Half of the following values, concatenated in order:

The Check space key (0x0043)
The AccountID of the sender of the CheckCreate transaction that created the Check object
The Sequence number of the CheckCreate transaction that created the Check object
```

any suggestions ?

**Comment by WietseWind** [comment]
As discussed: CheckID » Ledger Objects :)
In case of history (cashed check): modified meta objects: deleted object: Check ledger object.
