### ISSUE TITLE
Xumm API does not support X-address for POST /payload

### ISSUE THREAD

**Issue by nhartner** [XRPL-Labs/XUMM-Issue-Tracker#205]
I'm able to submit payloads using classic XRP addresses but not X-address. The following curl call fails with a 603 error (Error: Invalid Hex):

```
curl --location --request POST 'https://xumm.app/api/v1/platform/payload' \
--header 'x-api-key: redacted' \
--header 'x-api-secret: redacted' \
--header 'Content-Type: application/json' \
--data-raw '{
    "txjson": {
        "TransactionType": "Payment",
        "Destination": "XV5sbjUmgPpvXv4ixFWZ5ptAYZ6PD2q1qM6owqNbug8W6KV",
        "Amount": "100",
        "Fee": "12"
    }
}'
```

**Comment by WietseWind** [comment]
Hi @nhartner,

Thanks for reporting this! This is actually 'normal', the txjson is being used as the base transaction for composing the transaction to send to the XRPL, and the X-address codec isn't supported there (by Rippled, etc.). It's a format for client side encoding/decoding only. 

I don't feel doing server side decoding is a good solution, as a number of fields can contain addresses, like issuer addresses, multisign accounts, regular key accounts, etc. So better stick with the client side encoding/decoding, submitting the r-address and possibly the DestinationTag field to the `txjson` field.
