### ISSUE TITLE
[Improvement] Discreet Mode <RT>

### ISSUE THREAD

**Issue by SASchofield** [XRPL-Labs/XUMM-Issue-Tracker#210]
Description:
When app restarted after previously selecting discreet mode, balance is visible.

Reproducing 'bug':
Whilst in XUMM app 'Home' screen, select the eye button beside the account name. Exit the application, force close so it isn't running in the background. When the user returns to the application their balance is visible once more.

Expected behaviour:
When returning to the application, the balance should remain discreetly hidden. It behaves correctly if the application has only been minimised. Couldn't find an option to set discreet mode as the default.

Screenshots:
Unable to include screenshots at this time.

XUMM version: 0.5.0.3146229

Device Details:
* Manufacturer: Samsung
* Model: Galaxy Note 10+ 5G
* OS version: Android ver 10

Consider:
An option to select discreet mode as default.

**Comment by WietseWind** [comment]
@N3TC4T I've received this request a number of times. Can we add the hidden balance state to the XUMM database, so if closed hidden, it starts hidden again?

**Comment by WietseWind** [comment]
@N3TC4T I just tested this, the switch @ Settings is there and works. The state (start with the state the app closed with) doesn't seem to persist when the app is fully closed and starts again, is that on purpose?
