### ISSUE TITLE
[Bug] When balance + account hidden: copy account = copy dots

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#211]
When (eye icon) balances and account are hidden, when holding the account and copying, the hidden value (dots) get copied onto the clipboard, instead of the underlying r.. address.

**Comment by N3TC4T** [comment]
It's not possible to copy content when secureTextEntry is enable, just disabled the copy ability when privacy mode enabled.

**Comment by WietseWind** [comment]
That's a good alternative as well 👍
