### ISSUE TITLE
[Improvement] Allow issues + tokens (branding) without being in the shortlist

### ISSUE THREAD

**Issue by Wietse-Livingroom** [XRPL-Labs/XUMM-Issue-Tracker#212]
Right now, if a issuer+token is in the XUMM known accounts with icons, it'll be in the shortlist as well. Some tokens and issuers deserve a fancy icon + fixed names, without being in the shortlist.

**Comment by WietseWind** [comment]
Both the issuer and the currency now have a `shortlist` property.

If an issuer and possibly asset is in the list, **always** render their icons and use their names in the list with IOU's, etc. (so unchanged, no matter 1 or 0)

But: when tapping "Add asset", the list should only contain the issuers & assets where `shortlist` = **1**. So issuer shortlist = 1 asset = 0: show issuer, hide asset (unless no assets are 1, then just hide the issuer as well). If issuer shortlist = 0, hide all assets for this issuer. 

![image](https://user-images.githubusercontent.com/4756161/83997787-7483bf80-a95f-11ea-96ab-86bcad5c6098.png)

**Comment by N3TC4T** [comment]
Can you provide a sample in the backend ? So I can test my implementation.

**Comment by WietseWind** [comment]
Yeah, I can actually do that without any risk for current users as the value will just be ignored, as long as we put it back before release. `<Note to self>` (please remind me)

- Gatehub is enabled
  - Gatehub EUR is enabled
  - Gatehub USD is disabled (shortlist = 0)
- Bitstamp is disabled entirely
  - Underlying assets are enabled, but as the parent is disabled, they should be gone too

Reminder: even if they are disabled (issuer or specific asset), displaying the names & icons should still work :)
