### ISSUE TITLE
[Improvement] Allow signing Sign In requests with unactivated accounts as well

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#229]
When signing, the list with accounts to sign contains the activated, read/write accessible accounts.

Only the `SignIn` transaction type should allow unactivated to sign as well, as you may want to verify your identity somewhere before activating, or eg. verify owning a regular key.

**Comment by N3TC4T** [comment]
It's already like this, are you sure for `SignIn`, you don't get the unactivated accounts ?

**Comment by N3TC4T** [comment]
I see, I already implemented this but I missed something. will fix it

**Comment by N3TC4T** [comment]
when fetching payload the `TxJson` key should contain `"TransactionType" : "SignIn"` but it changed to `"SignIn": true`, that's why the app don't detect it as `SingIn` tx, it wasn't like this before.

**Comment by WietseWind** [comment]
For future reference: 
![image](https://user-images.githubusercontent.com/4756161/85712501-ac715d80-b6e8-11ea-895e-0c492b020c7f.jpeg)
