### ISSUE TITLE
[Bug] Socket is not connected after first app setup

### ISSUE THREAD

**Issue by N3TC4T** [XRPL-Labs/XUMM-Issue-Tracker#236]
**Describe the bug**
After fresh app initialise and changing the App root to the DefaultRoot the socket won't connect to the XRPL node

**Comment by WietseWind** [comment]
As a result of this bug (reported by users several times recently) sometimes the App would show (after the first start) that an imported account had 0 (zero) balance & transactions. The next start the balance would show. This is fixed now.
