### ISSUE TITLE
[Bug] Expired deeplink TX shows wrong message (handled by other client)

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#24]
When a deeplink opens the app and the transaction is expired (eg. try the link at https://wietse.nodum.io/test/expired-deeplink) the app shows a message that the transaction has been "handled by another client", which is not the case: the message should be different when expired.

If expired: "The request expired"
If not expired, but handled by another client: "This request is already resolved"

**Comment by N3TC4T** [comment]
Fetching mentioned payload `9fa3bd39-210c-4e3e-a5d9-57ee8c37648e` returns 403 from backend.

**Comment by WietseWind** [comment]
Ah shit, my mistake indeed. If handled by another client the expired message is only for that specific client, others shouldn't be able to interact with the payload anymore as it is bound to the handler (client) indeed.

Sorry :)
