### ISSUE TITLE
[Bug] App crash (iOS) when scanning a Coinbase destination QR from Home

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#248]
When using the Home QR scanner in XUMM to scan a destination, contents:
`xrp:rw2ciyaNshpHe7bCHo4bRWq6pqqynnWKQg?dt=123`
![image](https://user-images.githubusercontent.com/4756161/90681626-fb102380-e263-11ea-9621-a354144838aa.png)

... You will navigate to the send screen. If you add an amount and go Next, XUMM will crash.

**Comment by gnurag** [comment]
I can confirm that Xumm app crashes on Android as well when the above steps are followed to scan the given QR code.

**Comment by WietseWind** [comment]
Thanks for testing & confirming that for Android @gnurag :)
