### ISSUE TITLE
[Bug] Send, destination: better displaying of search results (origin)

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#25]
When using the "send" flow, entering the destination/search box, typing a substring, only the XUMM backend service is queried, while the entered substring may also match someone in the address book (eg. name or address).

These results should (if matches) be combined under their respective own "title", eg.

[Contacts]
..
..
[Search results]
..
..

**Comment by N3TC4T** [comment]
The query is already applies in both local contacts and xumm backend, and the types are separated by their icon

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-21 at 22 16 33](https://user-images.githubusercontent.com/6250203/77236767-da16aa00-6bc1-11ea-994d-081302e1be39.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-03-21 at 22 16 42](https://user-images.githubusercontent.com/6250203/77236769-df73f480-6bc1-11ea-849f-9c42acf15871.png)

**Comment by WietseWind** [comment]
Ah, that makes sense except the end user doesn't know what the icon is/means.

And because, before searching, the account origin is separated by a header (see screenshot below) it is a bit unintuitive to switch (in the same screen) from separating by header to separating by (unexplained) icon.

@thisistriss 

![image](https://user-images.githubusercontent.com/4756161/77301342-d41ee700-6cef-11ea-8d31-ca2867502c0d.png)

**Comment by N3TC4T** [comment]
Also we need to add the origin (bithomp etc ...) for the search result, as a tag etc ...

**Comment by WietseWind** [comment]
Yes, Icon and/or name, I guess. So
[address]
[name] » align right: icon (?)

Or maybe icon all the way on the left... @thisistriss

**Comment by WietseWind** [comment]
> Also we need to add the origin (bithomp etc ...) for the search result, as a tag etc ...

Already there (`source`):
![image](https://user-images.githubusercontent.com/4756161/78075629-2f627080-73a5-11ea-8fb0-32838b5b07f7.png)

Can be:
`xrplns`
`bithomp.com`
`xrpscan.com`
`xrpl`
`xumm.app`
`payid`
