### ISSUE TITLE
[Bug][Android] Setup passcode will fail in android API 24 – 25

### ISSUE THREAD

**Issue by N3TC4T** [XRPL-Labs/XUMM-Issue-Tracker#250]
**Describe the bug**
`Hi, I downloaded the XUMM app. When I open the app, it asks for me to create a 6 digit pincode which i enter and click next. It then asks me to verify the pincode. I reenter the pincode and click save and this does nothing
`

Samsung S6 edge, android 7.0

**Comment by WietseWind** [comment]
I have another report from @ttarfin at `Android LG K11` with Android `7.1.2`:

> Hi Wietse. I just tried to install XUMM on my phone (Android LG K11) and kant get past the Save Passcode screen. I get to enter it again i press Save and nothing happens. Is this a known problem?

**Comment by NetScr1be** [comment]
# Another instance:

- Reported In:
  - https://app.frontapp.com/open/msg_dr3d6yt

- Device
  - Xiaomi Redmi Note 3 Pro

- Android Version
  - unknown
  - The user was requested to provide this info but has not responded at the time of this report
 
- User-Provided Video
  - Shows user successfully entering passcode but verifying it (correctly) fails with ANR
  - No response from 'Next' button  
  - [Link to video](https://drive.google.com/file/d/127_8d1aGSnZyRSsJJHe4fsT1PTM3YsDq/view?usp=drivesdk)
