### ISSUE TITLE
[improvement] Android - Keyboard incognito mode support

### ISSUE THREAD

**Issue by HiddeSmit** [XRPL-Labs/XUMM-Issue-Tracker#258]
Please add support for the "incognito" API mode, so that keyboards like Google Keyboard (Android) do not update any personalized data such as typing history and personalized language model based on what the user typed.

Apps like Signal and Chrome (private navigation), implement this already.

I think the API which is needed is this one, however I'm not entirely sure:
https://developer.android.com/reference/android/support/v13/view/inputmethod/EditorInfoCompat#IME_FLAG_NO_PERSONALIZED_LEARNING

**Comment by HiddeSmit** [comment]
I guess I should've opened this on the xrpl-labs tracker? Want me to reopen this on the tracker instead?

**Comment by WietseWind** [comment]
@HiddeSmit This is the perfect place to create this issue, thank you 👍 

Let me loop @N3TC4T in to ask how he feels about this 👍 I believe I already discussed this and he had a good reason for not being able to implement this (or he already did? I don't remember, but he'll reply, I'm sure).

**Comment by N3TC4T** [comment]
@HiddeSmit Thanks, Will take a look at it.
