### ISSUE TITLE
[Clarify] Update r-address import screen

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#259]
On a daily basis, XUMM users ask why they see transactions / balances they can't explain after adding their Exchange deposit address as Read Only account. Some even think it's their address and send funds there from another wallet (which is a problem if they omit the destination tag because they think it's their own address).

There is a warning in the screen, but some/most users don't read it.

I suggest that we first show the message, then a countdown showing a button after hitting 0 AFTER the text, allowing them to tap "I understand", after which the input appears under the text. Only then an address can be added.

Then we do the existing Destination Tag required check (when sending accounts) and check for balances > 1 million, if one or both conditions are met, we show another alert that this appears to be an exchange address, are you sure you want to continue? You can never send to this address without respecting the instructions of your exchange. » Cancel / I understand

![image](https://user-images.githubusercontent.com/4756161/92027092-5b25c000-ed62-11ea-8250-81be1fb6f83c.png)

**Comment by NetScr1be** [comment]
> I suggest that we first show the message, then a countdown showing a button after hitting 0 AFTER the text, allowing them to tap "I understand", after which the input appears under the text. Only then an address can be added.

This is OK as a minimum.

I think you're nicer than me. I would do a lookup on the address and not allow any registered to exchanges. Yes, it would require maintaining a blacklist but, it's either that or have a continuing influx of support requests.

> Then we do the existing Destination Tag required check (when sending accounts) and check for balances > 1 million, if one or both conditions are met, we show another alert that this appears to be an exchange address, are you sure you want to continue? You can never send to this address without respecting the instructions of your exchange. » Cancel / I understand

Do all exchanges assign a permanent Destination Tag to their users?

It seems this wouldn't work with dynamic Destination Tags.

Or, I don't understand this.

**Comment by WietseWind** [comment]
@NetScr1be The problem with a blacklist is that it's never up to date, exchanges add and rotate new accounts for deposits al all the time, and new exchanges pop up every now and then, resulting in the first users being able to add, and after: not anymore. 

Some exchanges work with permanent tags, some with rotating / random ones.

Our current check is: fetch last X transactions from account, check filter on incoming, check if tag was present. If most of them had a tag present not being zero, it is most likely a custodial account.

**Comment by NetScr1be** [comment]
makes me wonder if there is use case for a directory service. Is there utility/value in linking and account to an OU?

Custodial account meaning holding assets on behalf of someone else?

There is a balance to be struck between allowing freedom to transact and protecting people from themselves.

The problem with trying to protect people from themselves is they are rarely grateful and will certainly look to blame if something goes wrong.

So my question is '_Is XRPL Labs accruing liability by taking measures to protect people from themselves_?'.

The answer is probably no or, at least, not much but the question needs to be consciously asked/answered when adding/changing functionality.

Don't mean to tell you how to run your business but that's what comes up for me.

**Comment by WietseWind** [comment]
I feel we *should try to* protect users, but there's only so much we can do. People will have to accept terms (post beta) before being able to use the app, and those terms will contain a disclaimer. As long as XUMM only offers non custodial services, that is.
