### ISSUE TITLE
xumm.app/sign/* - Broken layout when signing large Payloads

### ISSUE THREAD

**Issue by gnurag** [XRPL-Labs/XUMM-Issue-Tracker#263]
Xumm signing app's (https://xumm.app/sign/*) `Show raw` modal dialog needs to be flexible to accommodate large payloads. This issue can be reproduced while setting MessageKey for an account, and clicking on `Show raw xumm (advanced)` link.

![mk](https://user-images.githubusercontent.com/13650/93751231-61e57b80-fc1a-11ea-9e83-dbcc9ee5d116.png)

**Comment by WietseWind** [comment]
Fixed :) https://github.com/XRPL-Labs/xumm-api/commit/64c4c45edc4b577ca0dee2d5ee0b1c4922955d46?branch=64c4c45edc4b577ca0dee2d5ee0b1c4922955d46&diff=split

Thank you!
