### ISSUE TITLE
[Android] Unable to prepare the transaction 

### ISSUE THREAD

**Issue by Nonabz** [XRPL-Labs/XUMM-Issue-Tracker#264]
get a error by try to send XRP or sign up for airdrop Spark token.

Unable to prepare the transaction, Invalid character in ����t�M*z���t|��m�5x��1���Q�%����R����Y�+_~sr���K���E�֮+#I!|��b��:

Android 10 lineage OS

**Comment by WietseWind** [comment]
Timeout
