### ISSUE TITLE
[Improvement] Reduce caching TTL for resolved exchange names

### ISSUE THREAD

**Issue by gnurag** [XRPL-Labs/XUMM-Issue-Tracker#269]
Many exchanges re-brand themselves, get acquired, or sometimes there's better data to classify them. Due to this, the exchange labels are constantly monitored for accuracy and updated as needed. A case in point is BHEX that [rebranded](https://news.bitcoin.com/bhex-rebranded-as-hbtc-exchange-launch-innovative-hbc-10x-pe-repurchase-plan/) to [HBTC](https://xrpscan.com/account/rskZBJCS5ZygxsP2tAZ2gRCwSuyh9dgaXM). Xumm still resolves this to BHEX - perhaps the cache TTL needs to be reduced so exchange labels are fresh.

**Comment by WietseWind** [comment]
Do you have an account address for me, so I can check what is coming from where?

**Comment by gnurag** [comment]
`rNWLvz9K5bgNcLwUDPAKgnmfopZx3zSvg3` is a verified HBTC address.

**Comment by WietseWind** [comment]
Thanks! I just checked. We get our info from several community data sources, and in this case it's not our cache but the result we got from our friends at Bithomp. This was the live result from live calls:

```json
{
  "input": "rNWLvz9K5bgNcLwUDPAKgnmfopZx3zSvg3",
  "live": true,
  "cached": 1601287199,
  "explicitTests": {
    "emailAddress": false,
    "xrplAccount": true
  },
  "matches": [
    {
      "source": "bithomp.com",
      "network": null,
      "alias": "Blue Helix",
      "account": "rNWLvz9K5bgNcLwUDPAKgnmfopZx3zSvg3",
      "tag": null,
      "description": "bhex.com"
    },
    {
      "source": "xrpscan.com",
      "network": null,
      "alias": "HBTC",
      "account": "rNWLvz9K5bgNcLwUDPAKgnmfopZx3zSvg3",
      "tag": null,
      "description": "2"
    },
    {
      "source": "xumm.app",
      "network": null,
      "alias": "Blue Helix",
      "account": "rNWLvz9K5bgNcLwUDPAKgnmfopZx3zSvg3",
      "tag": null,
      "description": ""
    },
    {
      "source": "xrpl",
      "network": null,
      "alias": "rNWLvz9K5bgNcLwUDPAKgnmfopZx3zSvg3",
      "account": "rNWLvz9K5bgNcLwUDPAKgnmfopZx3zSvg3",
      "tag": null,
      "description": ""
    }
  ]
}
```

**Comment by gnurag** [comment]
Thanks for jumping in and the details on caching strategy, which seems very reasonable. I'm quire sure I saw `BHEX` a while ago, but none of the above listed data sources seem to label it as BHEX. I think it should be safe to close this issue.

**Comment by WietseWind** [comment]
@gnurag It's definitely possible you saw BHEX and didn't, later on. When we purge cache, a new lookup will be sent to the several API's and backends and the first one to reply wil populate the cache and determine the result we serve. If eg. XRPScan was a little faster (they are up to date, see example above) you got the right response.
