### ISSUE TITLE
[Bug][IOS] Cannot open link on non default browser

### ISSUE THREAD

**Issue by NetScr1be** [XRPL-Labs/XUMM-Issue-Tracker#270]
**Describe the bug**

In iOS, with default browser set to Brave (something other than Safari?), XUMM throws “ERROR Unable to open return url!”

**Steps to reproduce the behavior:**

This is the case reported via Intercom (text attached in xumm_xrpl_labs_2020_10_03_152601500000499.txt). No assumption it is the only instance.

1. Sign a transaction
2. Alert pops up with the a message to the effect of "Error: unable to open link"

**Expected behavior**

Return to browser window that triggered the transaction

**Screenshots**

_Redacted for Privacy_

![XUMM Unable to open link](https://user-images.githubusercontent.com/5115007/95004896-3a4dc600-05bf-11eb-9130-df8d7dc2b3cb.jpeg)

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 0.5.1 (unsure if user upgraded)

What device are you running XUMM on?

* Manufacturer: [Apple]
* Model: [?]
* OS version: [?]
* Platforms
  * [X] iOS
  * [?] Android

### Additional context

Intercom report (Redacted for privacy): 
[xumm_xrpl_labs_2020_10_03_152601500000499.txt](https://github.com/XRPL-Labs/XUMM-Issue-Tracker/files/5322529/xumm_xrpl_labs_2020_10_03_152601500000499.txt)

**Comment by WietseWind** [comment]
Based on: https://app.intercom.com/a/apps/nq9rb5du/inbox/inbox/all/conversations/152601500000499
