### ISSUE TITLE
[Bug] App crashes (iOS/Android) when scanning a PayID to add to address book

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#273]
App crashes instead of resolving PayID and entering address + optionally tag:

Reproduce:
1. Settings
2. Address book
3. New
4. Scan QR (address)
5. Show any PayID in QR format:

![image](https://user-images.githubusercontent.com/4756161/95830629-444a9400-0d38-11eb-8350-a1399300a0c8.png)

**Comment by N3TC4T** [comment]
lol fixed it yesterday before you post the issue 👍 

https://github.com/XRPL-Labs/XUMM-App/pull/39/commits/cff3002bfb5ebd994971cc08a7d5d15e01a3e9b4
