### ISSUE TITLE
[User Experience] Number formatting for Account balance display

### ISSUE THREAD

**Issue by gnurag** [XRPL-Labs/XUMM-Issue-Tracker#278]
### Description
For Xumm users with large XRP balance, it may be difficult to tell at a glance what their actual balance is: `138022099.096233 XRP`. Number formatting (internationalized using `react-intl` perhaps?) will reduce the cognitive overload and tell at a glance that they're looking at 138 million something something XRP balance: `138,022,099.096233 XRP`

This would be a great help for people with learning disabilities such as dyscalculia.

### Example
Tried with this account: `rEb8TK3gBgk5auZkwc6sHnwrGVJH8DuaLh`

### Screenshot
![xumm-balance](https://user-images.githubusercontent.com/13650/97653238-4d509a80-1a86-11eb-8da7-3238ec987cab.jpg)

**Comment by WietseWind** [comment]
Completely agree, thanks :)
