### ISSUE TITLE
[Bug] XRP Reserve calculation for 0 limit trustlines

### ISSUE THREAD

**Issue by gnurag** [XRPL-Labs/XUMM-Issue-Tracker#279]
**Describe the bug**
For some accounts, the XRP reserve calculation is incorrect. I suspect this is due to 0 limit Trustlines, but I could be mistaken. See screenshot for explanation.

**Steps to reproduce the behavior:**
1. Add Binance wallet `rEb8TK3gBgk5auZkwc6sHnwrGVJH8DuaLh` as a read only account
2. From the home screen, click on _Explain my balance_
3. Difference between `Account balance` and `Available for spending` does not tally with the sum of all items listed in `Reserved`.

**Expected behavior**
Difference between `Account balance` and `Available for spending` should be equal to the sum of all items listed in `Reserved`.

**Screenshots**
![xumm-iou](https://user-images.githubusercontent.com/13650/97654692-80e0f400-1a89-11eb-9329-2a9fa3685c37.jpg)

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 0.5.2.3146232

What device are you running XUMM on?

* Manufacturer: OnePlus
* Model: 7
* OS version: 
* Platforms
  * [ ] iOS
  * [x] Android

### Additional context
See the Trustlines `HKD.rMjx76hye8WjzGqaFmHnRXQbHSZweWCmzn`, `RPX.rEEL3tLXvSAo8oDgxfzWdTLN1Amoac2oCr` and `TRX.rULxE4M5mpVADiWdUhRJ7n6VPQWugMB7vY` they may provide some clue.

**Comment by WietseWind** [comment]
Another detailed report. Thank you @gnurag!
