### ISSUE TITLE
[Bug] Refresh known account settings after every transaction

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#28]
Report by @nixer89

> I opened the app. had an account A and an Account B. I set Account B as regular key for account A. Then I disabled the master key for Account A. Then I tried to enable the master key for Account A back and the transaction failed. (as info: I never left the "events" screen of the Xumm App!)
> But once I navigate to the "Home" screen, transactions are possible. My conclusion: After transaction submission and verification to the XRPL ledgter, the app does not refresh the account settings of all accounts, therefore is not aware that a regular key was set
> because it does not know of the new regular key, the app still tries to sign the next transaction with the master key
> once I navigate to the "Home" screen, the account_info's of all accounts are refreshed and the app is aware of the regular key relation and can sign the next transaction with the regular key 
> so is it possible to refresh the account_info (and even account_objects) after transaction verification? 

Suggested solution: refresh account info after sending a transaction that affects the account state, eg. `AccountSet`, `SetRegularKey`, ...

![image](https://user-images.githubusercontent.com/4756161/77180930-f08e0a00-6aca-11ea-8847-3e61795ddde3.png)

**Comment by WietseWind** [comment]
Needs review, does this still happen?

**Comment by nixer89** [comment]
I just tested the above described set up and it was working without problems for me

**Comment by WietseWind** [comment]
Perfect, thank you. I already remembered we may have fixed this at some point (or at least: something else affecting this ticket as well). Then I can close it 🎉
