### ISSUE TITLE
[Improvement] Safer "Slide to send" component for sign requests / manual send

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#289]
See:
https://xrpl-labs.canny.io/xumm/p/feature-add-slide-to-send

**Comment by WietseWind** [comment]
Note:
lower button (back, one step) = gone, upper left corner back = one step instead of back to home.

For both send flow and sign request flow

**Comment by thisistriss** [comment]
![image](https://user-images.githubusercontent.com/7113344/102874851-4d946300-4443-11eb-86e3-6a1844f63fd4.png)

**Comment by WietseWind** [comment]
Send: "Slide to send"
Request: "Slide to sign"
