### ISSUE TITLE
[UI improvements] Currency exchange panel: update fx rate & improve amount (typing)

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#29]
- When DEX exchange tab is opened, always fetch new rate (is preserved now when closed and reopened)
- When focussed: remove -0 (make empty) as now one may try to backspace without reason https://aoelg9f.dlvr.cloud/IMG_3618.png
- Blurring value should be possible by tapping outside of the input, so the "exchange" button becomes fully visible again. https://aoelg9f.dlvr.cloud/IMG_3618.png

**Comment by N3TC4T** [comment]
- Everytime the exchange view is opened, it will fetch the new exchange rate, as I checked there is not so order execution and price change at the time
- ....
- I cannot reproduce this as when you click on outside of keyboard it will blur the input.

**Comment by WietseWind** [comment]
@N3TC4T I can't reproduce the blurring either (anymore). This issue is superseded by #98 when implemented.
