### ISSUE TITLE
[Improvement, UI] Account Delete button

### ISSUE THREAD

**Issue by gnurag** [XRPL-Labs/XUMM-Issue-Tracker#298]
There's a button named `Delete this account` in `Accounts` > `Edit`  page. It gives an impression that clicking this button will delete the account from the ledger and recover the 20 XRP reserve. I haven't clicked it, but if its simply removing this account from Xumm's local account list, perhaps the button can be re-labelled as `Remove this account` or perhaps something else that's unambiguous?

**Comment by WietseWind** [comment]
That's a good suggestion, thanks. We'll include that in the next patch version :)

**Comment by gnurag** [comment]
Thank you! At the same time, it would be great to have real 'AccountDelete' functionality in Xumm :)

**Comment by WietseWind** [comment]
@gnurag That does make sense at some point, but I think it's a bit premature: there's insufficient knowledge and (more problematic) insufficient support from custodial services for receiving AccountDelete funds. Coinbase, Binance, Bitrue, etc. all do not pick up AccountDelete deposits, resulting in a lot of support pressure. Once there's better ecosystem support for AccountDelete transaction deposit receiving, I think it makes sense to add a really really really clear flow to do this.
