### ISSUE TITLE
[Bug] XUMM crashes at start on no internet connectivity

### ISSUE THREAD

**Issue by Wietse-Livingroom** [XRPL-Labs/XUMM-Issue-Tracker#299]
Confirmed on iOS, not tested on Android yet.

If the phone is in Airplane mode, starting XUMM will work (starts & stays alive). But: if airplane mode is OFF but there is NO internet, XUMM starts and crashes right after starting.

You can easily simulate this by:
- NO airplane mode
- Manually turn WIFI off
- Manually turn cellular off
- Now do a cold start of XUMM. After face ID / fingerprint XUMM crashes in about one second

https://xumm.zendesk.com/agent/tickets/10107

**Comment by Wietse-Livingroom** [comment]
@NetScr1be @KoenPaas FYI

**Comment by WietseWind** [comment]
Proposed solution:
1. Don't crash
2. Show a nice page/dialog that there's no internet connection
