### ISSUE TITLE
[Feature] Adding xApps: "XRPL dapp support" (enbedded, secure webapps)

### ISSUE THREAD

**Issue by yxxyun** [XRPL-Labs/XUMM-Issue-Tracker#302]
Add in dApp/app browser support, so that users can access xrptoolkit.com and other website which support xumm directly in the xumm app ,  all these websites just like a dapp on xumm/XRPL.
[example](https://user-images.githubusercontent.com/107192/103398431-ac5e8880-4b77-11eb-8e19-4fa3e30cf68a.jpg)

**Comment by WietseWind** [comment]
That's not a bad idea at all, something we discussed internally on a few occasions :) Possibly in the future. Thanks for the suggestion!

**Comment by WietseWind** [comment]
### Meta

Name: `xApps` (XUMM Apps)

### Design

**Comment by WietseWind** [comment]
More headers to add:
X-XUMM-Version
X-XUMM-Locale
X-XUMM-AccountType (Tangem, ...)
X-XUMM-AccountAccess (to, rw, rw-rk)

**Comment by WietseWind** [comment]
Awesome mockup by @thisistriss;

The highligted apps will be served in JSON format by the XUMM backend, based on the selected account. We'll serve a JSON feed with the four apps, name + icon URL, possibly based on what we want to highlight combined with the apps the user used most for the selected r-address. Initially the height will be reserved and the four icons will contain a skeleton, then to be replaced when we prefetched the JSON feed and icons. We'll only call this once per account per app session (cache).

Endpoint: `https://xapps.xumm.app/api/shortlist/account:rxxxx/version:1.0.1/locale:en-US/`

![image](https://user-images.githubusercontent.com/4756161/103811197-d83cab00-505c-11eb-9b28-9102bf94f840.png)

**Comment by WietseWind** [comment]
To Test (@WietseWind) and document:
- Getting params (headers)
- Origin for:
  - Push
  - Deeplink
  - Event
