### ISSUE TITLE
[Feature (Internal)] Add xApp direct launch (URL, push attribute)

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#303]
For eg.
- KYC flow
- On-ramp/off-ramp transaction inquiries 
- ...

Use the #302 full screen browser feature by directly launching into one (passing the headers already mentioned in issue 302). Deep link has already been registered;

On top of that the following header should be added:
`X-XUMM-Origin`: `<string>`
The value can be eg.:
- `PUSH_NOTIFICATION`
- `DEEP_LINK`
- `EVENT_LIST` (see below)

Sample deep link: https://p6jxppt.dlvr.cloud/index.html

Updating the [XUMM String Decode](StringType.XrplDestination) lib is not required, as the xApp URL's are native URL's already handled by our deep link handling.

Format:
#### eg. https://xumm.app/detect/xapp:app.xumm.aml-inquiry
(^^This full URL is the URL to open, backend updated: https://github.com/XRPL-Labs/xumm-api/commit/fa3cf7dc55ead3a4fffe0e55707e789408cffec9)

For push notifications, the data scheme to respect (if found: open):
`data.xappUrl: <string>`

Eg (see `data.xappUrl`) (POST to `https://xumm.app/api/v1/app/dev/push/raw`).

All `data` key-values should be passed into the browser view opened, on top of the ones already passed as specified in issue 302:
`X-XUMM-<KEY>`: `<VALUE>`

```
{
	"title": "XUMM fiat on ramp / off ramp",
	"subtitle": "Transaction information requested",
	"body": "€123,45 received (SEPA) from John Doe",
	"badge": 0,
	"sound": "default",
	"data": {
		"category": "OPENXAPP",
		"tx": "901AB6028204AE3EDB4D919EFC0BF36A25F73975674DCCA3FC54AEA85D9F56A0",
		"account": "rwietsevLFg8XSmG3bEZzFein1g8RBqWDZ",
		"xappUrl": "https://xumm.app/detect/xapp:app.xumm.aml-inquiry"
	}
}
```

![image](https://user-images.githubusercontent.com/4756161/104900770-c3c1b200-597c-11eb-910b-215aa7716373.png)

## Events

To allow users to get back to their open xApp-like requests, we'll show them in the `Events` - `Requests` list as well. To do this, we will use a `SignIn` pseudo transaction type, with a reserved property: 
`xappUrl`.
```
	"txjson": {
		"TransactionType":"SignIn",
		"xappUrl": "https://xumm.app/detect/xapp:app.xumm.aml-inquiry"
	},
```

The `pending-payloads` endpoint will return the payload results like this:
```
      "payload": {
        "tx_type": "SignIn",
        "tx_destination": "",
        "tx_destination_tag": null,
        "request_json": {
          "TransactionType": "SignIn",
          "xappUrl": "https://xumm.app/detect/xapp:app.xumm.aml-inquiry",
          "xappTitle": "Provide information",
          "SignIn": true
        }
      }
```

So if it's a SignIn reqeust and `payload.request_json.xappUrl` is present, when tapped, instead of opening the **Sign Request** flow, open the **xApp flow**.

The xApp logic is responsible for clearing (`DELETE`) the Event.

When the xApp dialog is opened from an Event, after closing the xApp dialog, the Event list should refresh (from the pending payloads endpoint) to make sure it's not displayed anymore if the actions in the xApp dialog cleared the Request.

The Request will be sent by an internal XUMM App, so the icon and title will already be clear in the overview. The subtitle (in the screenshot: `"Sign Request"`) should contain the value of the `xappTitle` property (see sample payload, "Provide information"). If there is no `xappTitle` is present in the SignIn pseudo tx payload, fall back to a new translation label with the English value: `Open for details`

![image](https://user-images.githubusercontent.com/4756161/104904492-7f84e080-5981-11eb-9815-b5301f3f04dc.png)

**Comment by N3TC4T** [comment]
@WietseWind, can you  include the `OPENXAPP` in the `data.category` as well ?

for sign request the value is `SIGNTX` and for xapp we can add `OPENXAPP`

so I can add this logic to the app

```
const category = get(notification, ['data', 'category']);
        switch (category) {
            case 'SIGNTX':
                return NotificationType.SignRequest;
            case 'OPENXAPP':
                return NotificationType.OpenXApp;
            default:
                return undefined;
        }
```

**Comment by WietseWind** [comment]
@N3TC4T of course, but I already added 'XAPP', see my description above the screenshot of the push notification. I can rename XAPP to OPENXAPP?
