### ISSUE TITLE
[Bug] Bypassing authentication

### ISSUE THREAD

**Issue by Dimitris24sta23** [XRPL-Labs/XUMM-Issue-Tracker#304]
Hi. I'm able to enter the app without authenticating (pin or fingerprint).

How to reproduce this:
Press to open the app and then press the back button to exit immediately. Then try to open the app again. You should be able to enter after 2-3 tries.

Im using a Samsung Galaxy S7 and have pin & fingerprint enabled. I run the app in the secure folder. (not sure if this has anything to do with the bug)

Cheers

* XUMM version: 1.0.1.3155731

* Manufacturer: Samsung
* Model: Galaxy S7
* OS version: 8.0.0

**Comment by WietseWind** [comment]
Hey! Thanks for the report! We'll dive right in and make sure to add a fix for the upcoming 1.1 release 😀 Appreciate the report, a lot!

**Comment by Dimitris24sta23** [comment]
@WietseWind You're right. You cannot do any action but only browse inside the app.
You can see a video here [https://dimitrisbor.s3-eu-west-1.amazonaws.com/xumm.mov](url)

Cheers

**Comment by WietseWind** [comment]
Hey @Dimitris24sta23,

Thanks! If I see it correctly, the first time you start the app, you do keep your finger on the fingerprint reader, right?
That means you already identified yourself.

If your XUMM app is set to only ask for startup auth every X time, it will not ask for new auth even if you start the app again, as it's time based, not "start based".

What is your `Auto Lock` setting in Settings - Security?

**Comment by Dimitris24sta23** [comment]
@WietseWind I only put my finger on the fingerprint reader just to enter the secure folder. Auto lock is at 0 seconds.
I've made a new video here: https://dimitrisbor.s3-eu-west-1.amazonaws.com/xumm_full.mov 
Hope it helps.

**Comment by WietseWind** [comment]
@Dimitris24sta23 Thanks for elaborating, I missed that part (just for secure folder). This definitely helps, we're on it, thanks!

**Comment by WietseWind** [comment]
@Dimitris24sta23 We (@N3TC4T actually) found & reproduced it. We'll fix it in 1.1.0 soon, thank you very much for reporting & helping us reproduce this!

**Comment by Dimitris24sta23** [comment]
@WietseWind I see this is fixed! Nice!
Here is my linkedin https://www.linkedin.com/in/dimitrisborbotsialos/
I'd be happy to connect with you
Thanks!
