### ISSUE TITLE
[UI] Prevent new line when wrapping long strings

### ISSUE THREAD

**Issue by KoenPaas** [XRPL-Labs/XUMM-Issue-Tracker#309]
A new line is created in certain UI elements when using other languages than english.

See Image below:
![A0621D02-A75C-452C-99F7-625EE1E09141](https://user-images.githubusercontent.com/36813373/107197766-9eace600-69f4-11eb-94cb-32b0d1bda092.jpeg)

**Comment by Wietse-Livingroom** [comment]
Agree,

### Proposal

Fix handling of longer translations: here's an example: when the app is set to German, the title of the Destination Tag screen is relatively long pushing the Next button out of bounds on an iPhone 12 Pro:
https://f1mxafd.dlvr.cloud/pasted_2.png

I think we should go through the app in Longer languages like French / German (they sometimes keep the English translation in place for reference as well) and see if we can:

- Try to fit & lower font size 
- Or:  just cut off with ellipsis: the user interface functioning is more important than the text (in a worst case scenario, that is)

**Comment by N3TC4T** [comment]
it's possible to adjust the font size to fit the text or we can  just cut off with ellipsis ?

<img src="https://user-images.githubusercontent.com/6250203/107502684-45ca8280-6b99-11eb-9e74-2800d569cc65.png"  height="200" />

**Comment by WietseWind** [comment]
@N3TC4T I think the ellipsis version is better. All the different font sizes (based on your screenshots) will be messy. The ellipsis solution will hopefully result in people using the translation portal to find shorter synonyms :)
