### ISSUE TITLE
[Bug] Green Next Button on 'enter destination tag' screen inaccessible when Language = Deutsche

### ISSUE THREAD

**Issue by NetScr1be** [XRPL-Labs/XUMM-Issue-Tracker#315]
[Ticket 10597](https://xumm.zendesk.com/agent/tickets/10597)

**Description**

- Next button on enter destination tag screen almost completely blocked when Language = Deutsche
    - Workaround: Switch language to English

**Steps To Reproduce**

0. _Reproduced on Android 11 Google Pixel 3a XL_
1. Set language to Deutsche
2. Walk through Send transaction set-up to 'edit destination tag' step
3. Fail

**Expected behavior**

Able to activate Next button from destination tag screen

**Screenshots**

_N.B. Both screenshots provided by client that reported issue_

## Bad (Deutsche)

![10597 Deutsch Destination Tag Screen](https://user-images.githubusercontent.com/5115007/108607903-5b0d9100-7391-11eb-9be0-71fcff399d83.jpeg)

## Good (English)

![10597 Destination Tag Screen](https://user-images.githubusercontent.com/5115007/108607708-f9005c00-738f-11eb-887d-b65038348dfd.jpeg)

### Environment

Customer advises latest Xumm version

* XUMM version: [Latest]

What device are you running XUMM on?

* Manufacturer: [Apple]
* Model: [iPhone 11 pro max]
* OS version: [IOS 14.4]
* Platforms
  * [X] iOS
  * [X] Android

### Additional context

N/A

**Comment by WietseWind** [comment]
Thanks!

The longer lines cause this. We're fixing this in 1.1 - relevant (similar) issue: https://github.com/XRPL-Labs/XUMM-Issue-Tracker/issues/309
