### ISSUE TITLE
[Feature] Make account selection screen sortable

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#317]
If you have multiple accounts in your XUMM wallet it is always troublesome to switch between accounts. Especially when you have like two accounts you use quite often and a few others you don't. When switching between the two heavy used accounts, the one I want to switch to is at the bottom of the account selection list (so I always have to scroll down to switch).

Therefore it would be really nice if the accounts in the account selection screen can be organized by the user so that he can choose the order of the accounts.

**Comment by Wietse-Livingroom** [comment]
Already added (development branch) to be released in 1.1 :D
