### ISSUE TITLE
[Bug] Account selection in "sign screen" unusable after swiping down overlay

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#318]
**Describe the bug**
When opening a payload and the "sign transaction" screen is shown in XUMM, one can choose different account to sign this transaction with. If you click on the arrow icon, the account selection menu opens. If you click "Cancel" in this screen, everything works fine and you can reopen the account selection in the sign screen. But if you swipe down the overlay account selection screen (instead of using the "Cancel" button), then it is not possible to open the account selection overlay again (the arrow button stays in the "opened" position in the sign screen).

**To Reproduce**
1. Open a payload
2. Open account selection overlay
3. Swipe down account selection overlay
4. See error (you can not open account selection again)

**Expected behavior**
After swiping down (closing) the account selection overlay I am able to open it again

**Video**
https://cis5xvi.dlvr.cloud/bug_account_selection_in_sign_screen.MOV

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: [1.0.1.1]

What device are you running XUMM on?

* Manufacturer: [Apple]
* Model: [iPhone SE 2020]
* OS version: [14.4]
* Platforms
  * [x] iOS
  * [ ] Android

**Comment by WietseWind** [comment]
Thank you!
