### ISSUE TITLE
[Improvement] Add re-register for Push Notifications option in Advanced settings.

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#319]
If there's a way to check Push Notifications functioning well, that'd be better. Check & re-register. Check » Sends call to backend » Sends push » XUMM waits for that push message » If not received in X seconds, offer to re-register?

In case of Nixer: he changed his phone, somehow his push isn't working now, maybe we can detect this and auto offer to re-register?

There is an endpoint for this from the `app` API context, using the existing credentials:
`/api/v1/app/dev/push/raw`

Sample content:
```
{
	"badge": 10,
	"sound": "default",
	"data": {}
}
```
Obviously the `badge` and `sound` element can be left out to not to change the Badge counter, and not to trigger vibration / audio (although for a user triggered test it may make sense to leave the sound so the user gets feedback).

To visually test, add:
```
"title": "XUMM Push",
"subtitle": "Wietse Testing",
"body": "Push Sample"
```

Persist new token with `/api/v1/app/update-device`:
```
{ 
  "devicePushToken": "abcd1234"
}
```

**Comment by N3TC4T** [comment]
We can also fetch the token from Firebase at the start of the app and include it in the `ping` endpoint, or just simply add the `re-register push notification` button in the advanced settings and call the endpoint with the push notification token gotten from firebase.

PS. getting token from firebase is not an expensive action,

**Comment by Wietse-Livingroom** [comment]
@N3TC4T You mean in case the token changed? I meant to test the token we already have. 
If you fetch from Firebase, would that include the scenario where push is revoked, or no longer valid as a user migrated phones (iCloud transfer, another device)? Wouldn't that require a new push permission request (re-register)?

**Comment by N3TC4T** [comment]
`getToken` will always returns the current working push token belong to device, if the push expired or user changed his device a new push token will be return firebase, so we can update the backend with new push token, I think exactly what signal app does.

**Comment by WietseWind** [comment]
@N3TC4T In that case I guess a button under `Advanced` to fetch, and then persist with `/api/v1/app/update-device` would be (more than) enough :)
