### ISSUE TITLE
[Bug] Input for family seed brings up 3rd party keyboard

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#321]
**Describe the bug**
When entering a family seed (as example copy&paste), the input brings up an installed 3rd party keyboard.

**To Reproduce**
1. Have a 3rd party keyboard installed on your iPhone
2. Add new account
3. Choose family seed
4. Click in family seed input
5. The 3rd party keyboard is opened

**Expected behavior**
It should not be allowed to have a 3rd party keyboard opened in security relevant fields like family seed, mnemonics, passcode and so on. Some of those keyboard store typed in data in a dictionary which is a security risk. Especially sometimes they will propose the saved family seed when typing random words.

I just checked for the family seed for now. Please also check for the other, security relevant input fields.

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: [1.0.1]

What device are you running XUMM on?

* Manufacturer: [Apple]
* Model: [iPhone SE 2020]
* OS version: [14.x]
* Platforms
  * [x] iOS
  * [ ] Android

### Additional context
Attach crash logs if available. Please ensure that these files do not contain any personal information.

**Comment by WietseWind** [comment]
Good point. And: good news: in XUMM 1.1 (under development) we're forcing the native keyboard throughout the app 🎉

**Comment by nixer89** [comment]
Please refer to 
https://github.com/XRPL-Labs/XUMM-Issue-Tracker/issues/135

I'm sure it was working already and I also tested it successfully. That's why I was surprised now that it wasn't working anymore 😇
