### ISSUE TITLE
[Feature] Add "Developer Mode" switch to settings

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#323]
I find myself sometimes submitting a transaction to the wrong network (main/test). Especially when testing stuff.

So my suggestion is to add a new option "Developer Mode" into the settings.
As a first step, if activated, the app shows the network / node it is currently connected to. (like in the header maybe?)

I think we could even come up with some more "features" for the "Developer Mode" :)

Edit: suggestion by @WietseWind 
"Or: we should add a "testnet requested" (or mainnet required) flag to payloads, and reject opening a payload meant for the other net."

I like that too since my website is fully mainnet/testnet compatible. Not sure how it is for other devs. it might be a problem for them?

**Comment by Wietse-Livingroom** [comment]
Good one I guess with a "Developer Mode" switch in Settings, we can show a TESTNET (GREEN) / LIVENET (BLUE) bannerlabel:
- At the home screen, near the balance
- At the SEND confirmation screen, above the Slide to Send button
- At the SIGN REQUEST screen, above the Slide to Send button
