### ISSUE TITLE
[Bug] Sorting accounts does not scroll automatically

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#327]
**Describe the bug**
When beeing in the "Accounts" view and trying to sort an Account: The view does not automatically scroll down when reaching the bottom of the screen. So if you have a long account list and want to move an account all the way down, you need multiple steps. (drag & drops) instead of only one drag & drop.

**To Reproduce**
1. Have a long account list
2. Sort an account from the top all the way to the bottom
3. Screen does not scroll down and you have to drop the account, scroll down, and touch/drag it again

**Expected behavior**
Screen scrolls down automatically when reaching bottom of the screen

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 1.0.9 (beta)

**Comment by WietseWind** [comment]
We will not be able to squeeze this in the upcoming release, but we'll look at this for the release after the upcoming one. For now, let's just move them per 3~4 positions, drop, scroll (swipe) and move again 😇

**Comment by N3TC4T** [comment]
This is already fixed in `2.3.0`
