### ISSUE TITLE
[Feature] Add Ed25519 key pair support

### ISSUE THREAD

**Issue by yxxyun** [XRPL-Labs/XUMM-Issue-Tracker#328]
https://github.com/XRPLF/xrpl-py/issues/185

**Comment by WietseWind** [comment]
Ed25519 key pairs (both when imported from family seed or raw HEX private key entered in the family seed field) are already supported.

**Comment by yxxyun** [comment]
Forgot to mention,  my ed25519 key is generated before https://github.com/ripple/rippled/pull/2734
and is not generated by ripple-lib with "sEd" beginning string,  so I guess it's a edge case.

**Comment by WietseWind** [comment]
The start with sEd is not required for it to work. 

Did you try it?

**Comment by yxxyun** [comment]
eg: 
seed: sarbwV6vkszxzHAYofms4L729UrMn
expect r-address: rLw7h2J9zRqtJMMCCxrp1zW4z1vJXbaBZp  (ed25519)

shown r-address: rwNoP9mwDzsar1WiDNhur8BG7kvEdvd25Z (secp256k1)

**Comment by WietseWind** [comment]
Ah, yeah, that one is pre `ed` prefix. Here's what we're going to do (for the upcoming version):
- You'll have to get the HEX private key for the account
- You can import the HEX private key into XUMM, using the Family Seed flow (but secretly importing the HEX private key)

Please note that this doesn't work yet, we'll have to implement something on our side as well.

To get the HEX private key:
1. Create a node file (to execute later) (see below)
2. Install `npm install ripple-keypairs`
3. Modify `ripple-keypairs` in `node_modules/ripple-keypairs/dist/index.js`: change `const algorithm = decoded.type === 'ed25519' ? 'ed25519' : 'ecdsa-secp256k1';` to `const algorithm = options.algorithm === 'ed25519' ? 'ed25519' : 'ecdsa-secp256k1';` (so: `decoded.type` to `options.algorithm`)

```
const {deriveKeypair, deriveAddress} = require('ripple-keypairs')

const seed = 'sarbwV6vkszxzHAYofms4L729UrMn'
const keypair = deriveKeypair(seed, {algorithm: 'ed25519'})
const address = deriveAddress(keypair.publicKey)
console.log({keypair, address})
```

Then run (`node ...js`) and you'll get the HEX private key:
![image](https://user-images.githubusercontent.com/4756161/114334346-aa2ea180-9b4a-11eb-8205-52c1ab54813e.png)

**Comment by WietseWind** [comment]
@yxxyun Heads up: we added this and it'll be in our 2.0 release expected any day now. To do this (when you obtained the HEX private key), when importing an account: select full access - family seed. Then paste (QR scanner won't pick up on it) the full hex private key starting with ED in the family seed input and XUMM will recognize & handle it.
