### ISSUE TITLE
[Bug] Transaction signing does not work in some sppecial circumstances

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#33]
Recap:

account_info (if a master key is disabled Y/N, if a regular key is set Y/N) isn't always up to date, resulting in signing with or without a regular key while that's no longer required (or no longer possible).

#### @N3TC4T Easy workaround "fix" = after all transactions involving AccountSet / SetRegularKey, force a fetch account info for all accounts.

---

**Description**
Signing of new Transactions via XUMM fails when:
1. Regular Key is set and you disable the Master Key
2. you Enable back the Master Key and delete the Regular Key

**To Reproduce**

There are two ways to reproduce it:

A:)

1. open the XUMM app and go to "Settings"
2. Receive a push notfication to set Account B as Regular Key of Account A and open + sign the transaction
3. Receive a push notification to "Disable Master Key" of Account A and open + sign the transaction
4. Receive a push notification to "Enable Master Key" of Account A and open + sign the transaction
5. Error occures from the XRPL saying "Master key is disabled"

![IMG_0409](https://user-images.githubusercontent.com/25486793/77303815-da16c700-6cf3-11ea-99de-47197c3a9d2e.PNG)

OR

B:)

1. Precondition: Account B is the Regular Key for Account A. Account A has it's Master Key Disabled
2. Receive a push to Enable Master Key for Account A. Open and Sign
3. Receive a push to Delete Regular Key of Account A. Open and Sign
4. Receive a push to sign a transaction (like setting a Domain). Open and Sign
5. Transaction fails with "Transaction's public key is not authorized"

![IMG_0408](https://user-images.githubusercontent.com/25486793/77303831-dedb7b00-6cf3-11ea-93f7-f370ffb21d73.PNG)

**Expected behavior**
The transaction should be signed with the Regular Key/Master Key. But instead it seems XUMM tries to sign with the Master Key/Regular Key

**Screenshots**
See above!

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 0.1.6.1

What device are you running XUMM on?

* Manufacturer: Apple
* Model: iPhone SE
* OS version: 13.3.1
* Platforms
  * [ x ] iOS
  * [ ] Android

### Additional context
Session Logs can not be provided because App crashes when opening the Session Log (separate Issue)

**Comment by WietseWind** [comment]
@N3TC4T Easy workaround "fix" = after *all* transactions involving AccountSet / SetRegularKey, force a fetch account info for all accounts.
