### ISSUE TITLE
[Improvement] Allow Regular Key to sign even if Main Account is Full-Access

### ISSUE THREAD

**Issue by NetScr1be** [XRPL-Labs/XUMM-Issue-Tracker#331]
Xumm currently will not allow the regular key account to sign transactions if the primary account is set to Full Access (i.e. key is present in Xumm).

Setting a regular key and downgrading main account access to read-only (either before or after setting regular key) changes the behaviour to only allowing the regular key to sign.

_N.B. Tangem cards only create the account on first use. If Xumm is connected to the testnet when the account is created the regular key will be a TestNet address. This still works to sign transactions on MainNet. Unsure (at this point) if there is any positive/negative effects from this._

In the case where the main account is a Tangem card, changing the current behaviour so Xumm allows the regular key to sign regardless of access level allows users to physically secure the main account card no matter the access level and removes an extra requirement from the process.

Users, even if instructed, are sure to find a way to not set the account to read-only so there is a side benefit in better user experience and one less source of Support traffic.

**Comment by WietseWind** [comment]
Now available in the released XUMM 2.1.1

**Comment by WietseWind** [comment]
Now available in the released XUMM 2.1.1
