### ISSUE TITLE
[xApp idea] Show account net worth (based on DEX)

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#335]
![image](https://user-images.githubusercontent.com/4756161/117190154-5f1d4c80-addf-11eb-8efc-6d73a505da20.png)

**Comment by KoenPaas** [comment]
https://github.com/XRPL-Labs/net-worth-xapp

**Comment by WietseWind** [comment]
@wojake Thank you for the suggestion. This is already being discussed here:
https://feedback.xumm.dev/xumm/p/account-worth-in-main-screen

That thread also contains my current arguments for not doing this at this moment ;)
