### ISSUE TITLE
[Bug] [iOS] Signin broken with a tangem card after closing and opening a signin request

### ISSUE THREAD

**Issue by KoenPaas** [XRPL-Labs/XUMM-Issue-Tracker#338]
This bug appears when trying to signin after closing and opening the request with a tangem card.

**To Reproduce**
1. QR scan the signin request.
2. close signin request in XUMM
3. Open signin request in XUMM and sign with a Tangem card
4. Indefinite spinner, no NFC popup.
5. Manually need to restart the app.

* XUMM version: 2.0.2.2
* Model: iPhone X
* OS version: Latest

**Comment by WietseWind** [comment]
@N3TC4T

**Comment by WietseWind** [comment]
@KoenPaas Discussed with Ali. This is actually fixed in the new Tangem SDK being rolled out in the upcoming XUMM 2.1 version 🎉
