### ISSUE TITLE
[Feature] Add custom wss endpoints through specially crafted QR code

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#342]
For eg. our own Hooks network to be used with XUMM, we'd need to be able to allow importing websocket endpoints.

We originally didn't add this for security reasons, but when eg. only allowing these endpoints to be imported with a special QR code, then to show a big fat warning, we could allow this anyway.

Something else we did is limit outgoing connections on the native side. We could extend this filter to include only websocket locations added this way (through this special QR).

After adding a custom endpoint, we should store them in a Custom section in the Settings - Advanced section, where they (only custom) can be deleted (swipe from right to left, normal pattern).

The same applies to the explorer URL.

https://egdnk2j.dlvr.cloud/pasted_1.png

QR contents could be something like (like the custom alphabet):
```
https://xumm.app/detect/feature:network-endpoint?type=custom-endpoint&name=Hooks%20Testnet&endpoint=wss://hooks-testnet.xrpl-labs.com&explorer_tx=https://hooks-testnet.xrpl-labs.com/explorer/tx/%7Btxid%7D&explorer_account=https://hooks-testnet.xrpl-labs.com/explorer/account/%7Baccount%7D
```
Sample QR: https://kfibf7w.dlvr.cloud/pasted_1.png

XUMM String Decode output:

```
        "type": "XummFeature",
        "output": {
            "feature": "network-endpoint",
            "type": "custom-endpoint",
            "params": {
                "name": "Hooks Testnet",
                "endpoint": "wss://hooks-testnet.xrpl-labs.com",
                "explorer_account": "https://hooks-testnet.xrpl-labs.com/explorer/account/{account}",
                "explorer_tx": "https://hooks-testnet.xrpl-labs.com/explorer/tx/{txid}"
            }
        }
```

--- For endpoint security:

All custom websockets get proxied through:
wss://custom-node.xrpl-labs.com

Meaning that eg. `wss://hooks-testnet.xrpl-labs.com` will be connected to:

```wss://custom-node.xrpl-labs.com/hooks-testnet.xrpl-labs.com```

^^ This makes it easy for us to whitelist and monitor @ our proxy, and the native patch can simply add one domain.

**Comment by WietseWind** [comment]
New URL + QR format:
https://xumm.app/detect/feature:network-endpoint?type=custom-endpoint&hash=bcfabbc9da8f1b5ff37e
![image](https://user-images.githubusercontent.com/4756161/121591730-2144c100-ca3a-11eb-884a-4f58f8fc5335.png)

String decoder lib. has been updated.

Verification & extra info now at API endpoint (app context):
https://xumm.app/api/v1/app/valid-endpoints/{hash}
e.g.
https://xumm.app/api/v1/app/valid-endpoints/160e97ddd9958b4b0938

**Comment by sappenin** [comment]
Love this feature, thank you all for implementing it so quickly!!!

**Comment by nkramer44** [comment]
This is awesome!

Will xumm send a webhook call after a user scans one of these QR codes? I was thinking we could capture the `user_id` from that and send the `user_id` in subsequent xumm requests to enable push notifications, but not sure if that will work.

**Comment by WietseWind** [comment]
@nkramer44 To enable user push, signing a payload (can be a Sign In payload) is required:
https://xumm.readme.io/docs/pushing-sign-requests
https://www.npmjs.com/package/xumm-sdk (`Sdk.payload.create`)

**Comment by WietseWind** [comment]
Now available in the released XUMM 2.1.1

**Comment by elmurci** [comment]
@WietseWind has this feature been disabled in newer versions? (I am running `2.6.0.18` and it doesn't seem to be working)

**Comment by WietseWind** [comment]
@elmurci Correct, sorry. We're in between working versions. 2.5 and before was QR
2.6 it's broken
2.7 (upcoming, ~2 weeks) will have a nicer mechanism, where you can add it in https://apps.xumm.dev/ straight to your device.

**Comment by elmurci** [comment]
Thanks for the update @WietseWind!
