### ISSUE TITLE
[Improvement] Please supply the currency from the user settings in the xAppOttData object

### ISSUE THREAD

**Issue by ajochems** [XRPL-Labs/XUMM-Issue-Tracker#343]
On xApp start we execute: xummSDK.xApp.get(xAppToken)
It would be very useful if the returned xAppOttData object contains the user selected currency from the Xumm settings alongside the language which is already supplied. We can then use that same Xumm setting in our xApp to render fiat based values on that setting. So USD, EUR, GBP ... etc

**Comment by WietseWind** [comment]
Good point ;) We actually just added that to the 2.1 development :D 
https://github.com/XRPL-Labs/XUMM-Issue-Tracker/projects/4#card-62184838

So expect this to be included in the 2.1 release.

**Comment by WietseWind** [comment]
@ajochems TS definitions already updated, npm 0.5.1

**Comment by WietseWind** [comment]
Now available in the released XUMM 2.1.1
