### ISSUE TITLE
[Bug] Unable to close xApp overlay/signing pages if there is more than one opened

### ISSUE THREAD

**Issue by KoenPaas** [XRPL-Labs/XUMM-Issue-Tracker#348]
If an xApp opens two or more signing pages/overlay only one is able to close using the close button. The second one is non responsive to a close input either after signing or top right.

Tested on iPhone X v2.1.0.6

**Comment by WietseWind** [comment]
@KoenPaas How does an xApp open more signing pages? Can you please explain the process to reproduce, possibly include a screencap?

**Comment by KoenPaas** [comment]
It shouldn’t open twice it was a bug on my end however with that I discovered this bug, creating two payloads simultaneously resulted in a failure to close more than 1 overlay.

**Comment by WietseWind** [comment]
Thanks @KoenPaas - @N3TC4T and I discussed it just now and it's good to prevent a dev. mistake to pass on to users indeed. We'll implement a limit on the xApp command receiving side, so only one command per one second is processed. By that time the app state is aware that a dialog / flow opened.

**Comment by KoenPaas** [comment]
I found a way to open two xApp webviews, where the xApps wouldn't close as well. @WietseWind your suggested solution in that case wouldn't fix the bug. If you open a sign request in a xApp and open an xApp with a link the bug is reproduced. The one second limit in this case is probably not a solution. @N3TC4T

**Comment by WietseWind** [comment]
Good point, which means if an xApp is already open, we should prevent a new one from opening I guess, @N3TC4T (?)
