### ISSUE TITLE
[Bug] Sign TX screen addition of PartialPayment Flags text only when sliding accept bar

### ISSUE THREAD

**Issue by casinocoinmoney** [XRPL-Labs/XUMM-Issue-Tracker#354]
**Describe the bug**
When on the sign screen for a Gatehub payment, I can scroll the sign page fine for as long as I want to without problem, but as soon as I put my finger on the "slide to accept" button to start moving it, the "Flags PartialPayment" appears and extends the screen height some more.

**To Reproduce**
Make a payment using an issued currency with a fee from issuer (I used Gatehub USD or EUR to find this).  Scroll your finger around the sign screen (this will be normal scrolling behaviour).  As soon as you touch the slide to accept bar, the extra label for "Flags PartialPayment" appears.

**Expected behavior**
Expect that any flags for the tx to show on page popup, and without changes prior to signing.

**Screenshots**
https://youtu.be/ovH5cLCJy20

### Environment
iOS 14.7, XUMM 2.1.1.1

**Comment by WietseWind** [comment]
Nice find. That value should indeed be displayed continuously, not only while sliding.

**Comment by N3TC4T** [comment]
this only happens when XUMM add's the missing partial payment flag to the transaction (the flag is required when there is a issuer fee set on the issuer), for a quick fix you can add the partial payment flag when creating payload (`131072`)

**Comment by N3TC4T** [comment]
right, added a [fix](https://github.com/XRPL-Labs/XUMM-App/pull/54/commits/eefb592607df91039b6ef2c8300a2e7d9e3bb5ff) and will be included in the next release 👍

**Comment by N3TC4T** [comment]
Fixed in `v2.1.2`
