### ISSUE TITLE
[Improvement] For issued currencies with fees, show the user the fee structure of the payment TX

### ISSUE THREAD

**Issue by flyfoxuk** [XRPL-Labs/XUMM-Issue-Tracker#356]
**Describe the bug**
Currently there is no indication of the fee structure of some assets from issuers that charge a per-transaction fee  (eg. Bitstamp 0.2%, Gatehub 0.2%)

**Expected behavior**
On sign screen, an indication of the current fee structure, eg. "This token issuer charges a fee of 0.2% of this payment, which means the recipient will receive approximately XXXX.XXX USD"

### Additional context
Considered important when being directed to sign transactions from non-XUMM triggers (eg. third-party xApps) so that users are fully aware of the cost and don't perhaps wonder who took a bite out of their payment!

**Comment by WietseWind** [comment]
This must definitely be displayed, as people must be informed what the effect will be of them signing a transaction. Thank yoy!
