### ISSUE TITLE
[Idea] Signing transactions offline using XUMM.

### ISSUE THREAD

**Issue by w0jak3** [XRPL-Labs/XUMM-Issue-Tracker#361]
Add a way to sign transactions offline in XUMM, when a transaction has been signed;
Display QR code of the transaction, this QR code can be used/sent using an online phone with XUMM.

0. User input: Wallet sequence, ledger sequence, fee, destination, amount

1. After the proper information has been inserted, a QR code will pop up on the screen.
2. This QR code *must* be scanned in an online phone using XUMM.
3. Once this has been scanned, the online phone must somehow authorize this transaction (Enter password, Slide to accept).
4. Online phone will then send the signed transaction to a XRP-L Node.

**Comment by WietseWind** [comment]
Duplicate: #201
