### ISSUE TITLE
[Improvement] Show spendable balance mutations for transactions updating Account OwnerCount

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#362]
Many users get confused with specific transaction types, like:
- Creating an offer
- Removing an offer
- Creating an escrow
- Finishing / Cancelling an escrow]
- Adding a Trust Line
- **Most of all**: Removing a Trust Line

Their spendable balance changes people want to be able to understand based on the Event list why their balance on the home screen mutated in a certain way. 

Worse: if users don't know (because of other activity) what their balance was vs. what it is e.g. after removing a TrustLine, they want to know if they "got their reserve back", check the Events and they don't see an amount received in the Event list for the removal of their Trust Line. Because of this they feel like they may not have gotten their reserve back as spendable balance.

To prevent confusion, support & give the users a safer feeling, I propose we add some changes.

## 1. Transactions contain modified node info for the Account with a changed `OwnerCount` if a transaction affected the reserve.
![image](https://user-images.githubusercontent.com/4756161/133993444-f02b00d7-bc45-484c-b3e9-3396241917ef.png)

## 2. For all transactions in the Event list and at the Event Detail page, if for **our own, watched** account, the transaction affected the **OwnerCount**, we will show the network Reserve with a lock icon.

- [ ] If the OwnerCount increased (lock up happened) the lock is closed. Of the OwnerCount decreased, the lock is open (unlocked).

- [ ] If there is already another amount displayed, show the regular amount & the reserve change below. 

This gives users visual feedback that the reserve (spendable balance) was **indeed** updated, and they **indeed** got some spendable XRP back.

![image](https://user-images.githubusercontent.com/4756161/133993878-23d3d192-8fd2-410f-9741-bbf725c310b3.png)

Also:
- [ ] The title should be updated from `Reserved` to `Reserved on the XRP Ledger`
- [ ] The total (re using the lock icon) should be on top:

![image](https://user-images.githubusercontent.com/4756161/133996333-7e091a3c-a98e-4ca2-a928-eb5864ac5928.png)

## 3. The Event details (transaction) page shows (text) that the transaction affected the reserve, and allows the user to pop up the "Explain balance" panel.

- [x] Header: `Reserve`, text: `This transaction {increased/decreased} the account reserve by {network owner reserve} XRP`.
- [x] Below there's a button: "My balance & reserve" which opens the Explain balance panel

![image](https://user-images.githubusercontent.com/4756161/133994033-d627bfdf-24cf-4050-b243-d895cb015f9b.png)

## 4. If we haven't covered a specific Reserve scenario, there may be a difference between the sum of Reserved & totals @ the balance Explain panel

If we didn't cover a specific reserve scenario or have our logic wrong, or aren't in time updating the source for future XRPL amendments, there may be a difference between the sum of the Reserved items and the difference between Account balance and Available for spending. To prevent confusion, we should detect and at least show something to make things add up:

- [ ] **IF** `Account Balance` - `Available for Spending` !== `sum(Reserved), **THEN** add a line at the end of the Reserved section: "Other (see ledger explorer): {[Account balance] - Available for spending] - sum(Seserved)} XRP`

![image](https://user-images.githubusercontent.com/4756161/133994309-a2cd3d20-37bc-44da-b01f-c3864fdeb47f.png)

**Comment by NetScr1be** [comment]
This is all good.

The only build I would throw in is somehow communicating that reserves don't leave the account. That only the availability in the account changes.

**Comment by WietseWind** [comment]
@NetScr1be I hope / think we achieve this by:
1. Showing a Lock/Unlock icon instead of in/out
2. On the detail page, add a button to the Explain panel where users see their total balance, reserve & spendable. 

Maybe an extra line with some text at point 2. would make sense? Do you have a suggestion?

**Comment by NetScr1be** [comment]
Something like:
`
Be Advised Total Balance will not change when reserves are allocated or released.

Available balance may change if account is not in deficit.`

Multiple tickets are from accounts in deficit where reserve owed is less than available.

**Comment by N3TC4T** [comment]
Closing this issue as it's already added in `v2.2.0`
