### ISSUE TITLE
Developer Docs - OUT OF DATE

### ISSUE THREAD

**Issue by dangell7** [XRPL-Labs/XUMM-Issue-Tracker#366]
In the developer docs here [](https://xumm.readme.io/docs/payload-status) you have the following:

```
"userToken": {
  "user_token": "<some-token>",
  "token_issued": "2020-01-20T15:41:30.575Z",
  "token_expiration": "2021-01-19T15:41:30.575Z"
}
```

however the actual response was:

```
"userToken": {
  "user_token": "<some-token>",
  "token_issued": 1234567890,
  "token_expiration": 1234567890
}
```

The thing to notice is that the `token_issued` and the `token_expiration` is not a string but a number. I was using swagger so the call was failing.

Please update the developer docs. :)

**Comment by WietseWind** [comment]
Oops! Thank you, great suggestion. We switched from time string to unix timestamp in the early days indeed. Updated the docs, thank you 🤗 

This needed a change in our SDK as well:
https://github.com/XRPL-Labs/XUMM-SDK/commit/2eaeea37133cd9f95e3ab35058e779f34155aa0e
