### ISSUE TITLE
[Bug] The login passcode can be bypassed by resizing the app's window in Android Desktop Mode 

### ISSUE THREAD

**Issue by kreaninw** [XRPL-Labs/XUMM-Issue-Tracker#370]
**Describe the bug**
The login passcode that users have to enter can be bypassed by resizing the app's window in Android Desktop Mode. This mode is called Productivity Mode by Lenovo.

![Screenshot_2021-12-25-00-53-00-116](https://user-images.githubusercontent.com/1403194/147377234-d9022ace-45f2-48ba-ae33-0dfba5eb56c7.jpeg)

The desktop mode on Android devices was introduced since Android 10 as a developer option. However, most, if not all, Android 11 devices now make this mode available on differences names.

**To Reproduce**
1. Enter the desktop mode on Android device.
2. Open Xumm app.
3. Resize the app's window.
4. The passcode screen will disappear. Then the users can use the app like the passcode never existed.

**Expected behavior**
The passcode should never be bypassed by any means.

**Screenshots**

https://user-images.githubusercontent.com/1403194/147377157-598b6baf-fdd8-4325-bef3-d70790ba663f.mp4

### Environment

* XUMM version: 2.2.5.3165984

What device are you running XUMM on?

* Manufacturer: Lenovo
* Model: Tab P 11, TB-J606L
* OS version: 11
* Platforms
  * [ not ] iOS
  * [ I'm using ] Android

### Additional context
Edit: The passcode screen was blacked out because the security feature of the app.

**Comment by WietseWind** [comment]
Thank you for reporting this!

@N3TC4T can we force app window size in environments like these?
