### ISSUE TITLE
[Feature] Ability to export events

### ISSUE THREAD

**Issue by sreckoo** [XRPL-Labs/XUMM-Issue-Tracker#373]
Hi. I was thinking of "nice to have" functionality to be able to export events into text file for further processing or analysing. 

Thank you for keeping up with this great project!

**Comment by WietseWind** [comment]
Thank you!

The Events are merely a view of all the transactions on the XRP Ledger for the specific account. There are no XUMM specific transactions.

You can use any client or tool to query the XRP Ledger. We created this open source sample: 
https://transaction-exporter.xrpl-labs.com/

Any blockchain explorer shows the same results, e.g. bithomp.com / xrpscan.com / ...

**Comment by sreckoo** [comment]
Thank you for the link you provided, that's very useful. I know there are blockchain explorers, and I guess from xrpscan.com I need to look bit more into json it produces to sort out the data in proper way.
