### ISSUE TITLE
[Bug] OfferCreate + Ticket results in "Invalid Payload" error in XUMM.

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#378]
When using Tickets, a transaction needs to include a TicketSequence, and it's mandatory to keep the Sequence field and the value must be zero (0).  (below)

Specifically for an `OfferCreate` transaction, when a payload is sent with Sequence 0 and TicketSequence, XUMM rejects the payload: https://hnvvbjy.dlvr.cloud/pasted_1.png

This (a TicketSequence, and Sequence 0) should be valid (for all transactions)

```
{
"txjson": {
          "TransactionType": "OfferCreate",
          "Account": "rwietsevLFg8XSmG3bEZzFein1g8RBqWDZ",
          "Sequence": 0,
          "TicketSequence": 1117,
          "TakerGets": {
            "currency": "EUR",
            "issuer": "rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq",
            "value": "0.01"
          },
          "TakerPays": {
            "currency": "USD",
            "issuer": "rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq",
            "value": "1"
          }	
}
```

**Comment by N3TC4T** [comment]
Fixed in https://github.com/XRPL-Labs/XUMM-App/pull/69/commits/dc4f344b113aada944a6fe3919f177f7446f0dfa
Publishing as `v2.2.8`
