### ISSUE TITLE
Feature: show the NFT price on sign page

### ISSUE THREAD

**Issue by KoenPaas** [XRPL-Labs/XUMM-Issue-Tracker#383]
Introduce the amount you're going to trade an NFT for.

On the transaction explorer details in XUMM you can see the price but not on the signing page as requested by a XUMM user:

![c7ba635a-1f39-46da-bcaa-450bb355e9bc](https://user-images.githubusercontent.com/36813373/157481652-d68a9449-2d52-4add-8342-91640f0d3d7c.png)
![9216513e-5f40-49d0-b24c-8e4cf642990a](https://user-images.githubusercontent.com/36813373/157481674-fbeffc39-3bc6-407d-a8ed-a45ebe2bfef5.png)

**Comment by WietseWind** [comment]
Hi @niraj-khatiwada, may I invite you to post questions / developer questions / issues (so: non bugs, non user stories) on our developer questions board? https://xumm.readme.io/discuss - this keeps our existing tickets & issues clean.
