### ISSUE TITLE
[Bug] Missing translation on create account screen

### ISSUE THREAD

**Issue by KevinKoobs** [XRPL-Labs/XUMM-Issue-Tracker#387]
**Describe the bug**
There is a missing translation on de create account screen

**To Reproduce**
1. Go to 'Accounts'
2. Click on 'Add account'
3. Create new account (I added a Tangem card)
4. When imported, read the prompt that says "The account hasn't been activated yet".
5. In the last alinea it states: `[missing %{baseReserve} value]`

**Screenshots**
https://pgvwdix.dlvr.cloud/pasted_2.png

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 2.2.8.3166009

What device are you running XUMM on?

* Manufacturer: Samsung
* Model: Galaxy A52
* OS version: Android 12
* Platforms
  * [ ] Android

**Comment by N3TC4T** [comment]
Fixed in https://github.com/XRPL-Labs/XUMM-App/pull/89/commits/c6491dc09853309a9080350460cd744cfce56639
