### ISSUE TITLE
[Bug] Sending TrustSet transaction to XUMM results in weird error

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#39]
**Describe the bug**
When sending a TrustSet transaction to Xumm, an weird error is shown after signing the transaction

**To Reproduce**
1. Send a TrustSet transaction to Xumm
2. Sign the transaction
3. See error

**Expected behavior**
Even if the TrustSet transaction is not valid, a proper Error message should be shown

**Screenshots**
![grafik](https://user-images.githubusercontent.com/25486793/77527457-6fe55a00-6e8c-11ea-9bb5-b979b56d03dc.png)

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 0.1.6.1

What device are you running XUMM on?

* Manufacturer: Apple
* Model: IPhone SE
* OS version: 13.1
* Platforms
  * [x] iOS
  * [ ] Android

### Additional context
the submitted payload looks like this (and was signed with testnet account):

```{"options":{"expire":5},"txjson":{"TransactionType":"TrustSet","LimitAmount":{"issuer":"rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq","currency":"ABC","value":"100"}},"custom_meta":{"instruction":"- Issuer Address: rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq\n- IOU currency code: ABC"}}```

SessionLog cannot be copied because the app shows only a white screen. Only after force closing the app it's working again but SessionLog is overwritten.

**Comment by WietseWind** [comment]
Reason: Testnet & the default testnet server was amendment blocked. This will add a message in the debug log in the future so it's easier to find the cause of the problem.
