### ISSUE TITLE
[Improvement] Report WSS endpoint to OTT data

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#390]
Currently, when an xApp is opened, OTT data is available for xApp developers like this:

```javascript
{
  "version":"2.2.8",
  "account":"...",
  // ...
  "nodetype":"MAINNET"
```

The `nodetype` MAINNET and TESTNET is all a dev needs to know to connect to those networks, but if an alternative network is used like a side chain or e.g. XLS20 devnet, it's up to the dev to guess if the client is connected to the right network. 

To allow devs to decide if they want to & can service end users on the network they are connected to, and to show clear instructions to switch nodes to end users, the `wss://` endpoint should be returned in the OTT data as well. This way devs can immediately setup a connection to the correct endpoint.

Proposed addition:
```
  "nodeurl": "wss://some-node-URL",
```

**Comment by WietseWind** [comment]
@KoenPaas FYI

**Comment by N3TC4T** [comment]
I just checked the code and if user is connected to a custom node, in the OTT data the node user connected to is present in the `nodewss` field. so this is already implemented in the app under different field name.

**Comment by WietseWind** [comment]
Ahhhh @N3TC4T that's awesome :D I never noticed because I am usually on the live/test/devnets :)

I now normalized the behaviour on the backend, where the default nodes are reported based on the selected network, and if custom, the reported `nodewss` value is reported with `wss://` prepended.

![image](https://user-images.githubusercontent.com/4756161/163283813-96f6b138-ad13-4127-aaa7-c3474b34e420.png)
