### ISSUE TITLE
[Improvement] When importing an account that has a disabled master key show correct label

### ISSUE THREAD

**Issue by KoenPaas** [XRPL-Labs/XUMM-Issue-Tracker#391]
When Importing an account with it's master key disabled it should show the correct label like: Master disabled instead of Read Only account.

This has led to confusing by users and our own support.

**Comment by N3TC4T** [comment]
https://github.com/XRPL-Labs/XUMM-App/pull/89/commits/1472fe3e44e28424cf0e99fa99320a8bc3676f1a
