### ISSUE TITLE
Signing with Tangem backup returns;  tecNO_LINE_REDUNDANT 

### ISSUE THREAD

**Issue by NetScr1be** [XRPL-Labs/XUMM-Issue-Tracker#393]
**Describe the bug**

Selecting backup Tangem card to sign from one screen returns;

```
 tecNO_LINE_REDUNDANT

Can’t set non-existent line to default.

```
Using primary card works.

Selecting backup card in transaction review screen works

Reported in: https://xumm.zendesk.com/agent/tickets/31734

**To Reproduce**

When removing a trustline the card to sign the transaction can be chosen in two ways; 

1. Review transaction (see 31734.1.png)

2. Signing (see 31734.1.png)

Selecting back up card in scenario 1 gives the error eventually.

Selecting back up card in scenario 2 works.

**Expected behavior**

Should be able to sign transaction no matter how the signing account is selected

**Screenshots**

****31734.1.png****

![31734 1](https://user-images.githubusercontent.com/5115007/167630519-bd57c4d1-3051-49e5-8593-f084fa32899d.png)

****31734.2.png****

![31734 2](https://user-images.githubusercontent.com/5115007/167630587-02121b4f-0d68-4a5a-937e-6fed28c6b348.png)

### Environment

2.2.8 @ MAINNET (TANGEM/FULL)

What device are you running XUMM on?    <<<< PENDING <<<<<<<<

* Manufacturer: [FILL THIS OUT]
* Model: [FILL THIS OUT]
* OS version: [FILL THIS OUT]
* Platforms
  * [X] iOS
  * [ ] Android

### Additional context
Attach crash logs if available. Please ensure that these files do not contain any personal information.

**Comment by WietseWind** [comment]
This is unrelated to Xumm and unrelated to Tangem cards. This simply means the person is trying to remove a Trust Line that isn't there to begin with:

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/4756161/167647547-1743f000-79e2-48d9-ae11-e88f826b52c7.png">

See the error code list:
https://xrpl.org/tec-codes.html

**Comment by NetScr1be** [comment]
That is in the ticket.

The transaction is successful when using the primary card (as per the client0.

Will try to reproduce.

**Comment by WietseWind** [comment]
If it was already processed using the primary card, it will fail with the other card, because the TrustLine then doesn't exist anymore ;)
