### ISSUE TITLE
[Bug] dev network: xls-20 default explorer

### ISSUE THREAD

**Issue by ihomp** [XRPL-Labs/XUMM-Issue-Tracker#408]
**Describe the bug**
If I choose xls20 network and check a transaction in xumm, and if I click check in the browser, it opens an invalid link like:
https://gregweisbrod.comf140e137cbd95a560a33c52022c2e2ac74d3f8430bda1737a0e3231203304/

**To Reproduce**
1. Scan QR code shared by Wietse to add xls20-sandbox.rippletestnet.net network
2. set node: xls20-sandbox.rippletestnet.net
3. explorer will show: "Node determined" 
4. go to account transaction
5. choose a transaction, click "..."
6. click "open in browser"
7. it redirects to https://gregweisbrod.comf140e137cbd95a560a33c52022c2e2ac74d3f8430bda1737a0e3231203304/ 

**Expected behavior**
I guess the link is supposed to be not broken.

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).
* XUMM version: 2.3.1.2

What device are you running XUMM on?
iOS, iPhone 12

if you choose a custom network, the explorer locks to "Node determined",
if you change to another network, like mainnet or testnet, "explorer" will still show "Node determined", unless you close the screen and get back to it. 

we have different explorers for different networks like
xls20.bithomp.com (xls-20d ripple)
beta.bithomp.com (hooks v2 xrpl-labs)
hooks.bithomp.com (hooks xrpl-labs)
test.bithomp.com (testnet ripple)

if you don't want to manage the list of bithomp explorers for dev networks 
we can add a redirect in the nginix for bithomp links with a networkwebsocket get param

for example:
https://bithomp.com/explorer/txid?networkwebsocket=wss://xls20-sandbox.rippletest.net:51233 
we can redirect that to
https://xls20.bithomp.com/explorer/txid

**Comment by N3TC4T** [comment]
Thanks viacheslav, I believe we never changed the explorer's links for the XLS20 custom node, nice catch, We will change it to the bithomp explorer 👍 

@WietseWind, right now the explorer for this custom node is 

```{"account": "https://gregweisbrod.com", "tx": "https://gregweisbrod.com"}```

We need to change it to 

```{"account": "https://xls20.bithomp.com/explorer/", "tx": "https://xls20.bithomp.com/explorer/"}```

**Comment by WietseWind** [comment]
Thanks @ihomp and @N3TC4T! That's still in there from pre XLS20 devnet golive 😇 Oops.

I just fixed it as per @N3TC4T's change, and this has been deployed. However, this is only picked up on import (afaik) meaning that the custom node first has to be removed (swipe left, delete) then to be added (QR scan) again for the new values to be picked up.

Thanks again for noticing and reporting!
