### ISSUE TITLE
[Bug] Global id profile link leading to 404

### ISSUE THREAD

**Issue by N3TC4T** [XRPL-Labs/XUMM-Issue-Tracker#410]
[Viacheslav](https://github.com/ihomp) broth this to our attention that Global id profile link from `api/v1/platform/account-meta` endpoint is incorrect and will lead to 404 page

Right now the endpoint returns the Global id profile in such format: `"profileUrl":"https://global.id/n3tc4t"` 
this should be change to `"profileUrl":"https://app.global.id/u/n3tc4t"`

Example: `https://xumm.app/api/v1/platform/account-meta/rs5qWu2XQmVc1vgFxeCtVymKBJq9iB7mCP`

**Comment by WietseWind** [comment]
Ah, the joy :) They changed their Profile URLs indeed. I updated the endpoint 👍
