### ISSUE TITLE
[Improvement] Add support for shortened payload UUID

### ISSUE THREAD

**Issue by DominiqueBlomsma** [XRPL-Labs/XUMM-Issue-Tracker#413]
Add support for shortened payload UUID in the QR Scanner and OS deeplinks.

Format: `xumm://00000000-0000-0000-0000-000000000000`

Support has already been added in XRPL-Labs/xumm-string-decode@6f6c8720e927d65a06865b0f3e1579de1a41874d

**Comment by Nanimustshine** [comment]
> Add support for shortened payload UUID in the QR Scanner and OS deeplinks.
> 
> Format: `xumm://00000000-0000-0000-0000-000000000000`
> 
> Support has already been added in XRPL-Labs/xumm-string-decode@6f6c8720e927d65a06865b0f3e1579de1a41874d

Kindly file a support ticket for this concern below
https://forms.gle/2FJfLTLbdCm1DW6C8

**Comment by N3TC4T** [comment]
Already implemented 🎉
