### ISSUE TITLE
[Improvement] Button misalignment when deleting node list

### ISSUE THREAD

**Issue by develoQ** [XRPL-Labs/XUMM-Issue-Tracker#419]
**Describe the bug**
The vertical position of the button is slightly off when deleting a custom node on the node list screen.

![IMG_2859](https://user-images.githubusercontent.com/69445828/198655894-76572f36-5a19-4c2f-8459-44684d0d3fac.png)

**Comment by N3TC4T** [comment]
Thanks, a fix has been applied and it's gonna be included in the next releae.
