### ISSUE TITLE
[Translation][JA]  home.addAccount 

### ISSUE THREAD

**Issue by develoQ** [XRPL-Labs/XUMM-Issue-Tracker#421]
The Japanese translation of `home.addAccount` should be `add account`.

The current `アカウントを追加する` breaks the string within the button.

`account.switchAddAccount` contains the same string, but no design corruption occurs.

`home.addAccount `
![IMG_2861](https://user-images.githubusercontent.com/69445828/198669270-fc41aec4-af19-4fab-8ca6-8722c7f8b2f4.jpeg)

`account.switchAddAccount`
![IMG_2862](https://user-images.githubusercontent.com/69445828/198669925-c91cf21b-2ed3-4b54-a097-16b8bbf14ec9.jpeg)

**Comment by N3TC4T** [comment]
Fixed in https://github.com/XRPL-Labs/XUMM-App/pull/89/commits/c6491dc09853309a9080350460cd744cfce56639
