### ISSUE TITLE
[Translation][JA] global.edit

### ISSUE THREAD

**Issue by develoQ** [XRPL-Labs/XUMM-Issue-Tracker#422]
I think the Japanese translation of `global.edit` should be `編集`.

In the case of `edit`, the string breaks within the button.

There does not seem to be any other place where `global.edit` is used.

![IMG_2863](https://user-images.githubusercontent.com/69445828/198674809-82b8da1b-7160-4d0c-b2f4-1aaadd463cdf.jpeg)

**Comment by develoQ** [comment]
Sorry for proposing multiple small translations.

I want Japanese XRPL users to be more comfortable using Xumm.

**Comment by develoQ** [comment]
If it would be better for your work if the translation corrections were combined in one Issue, please let me know.

**Comment by N3TC4T** [comment]
Fixed in https://github.com/XRPL-Labs/XUMM-App/pull/89/commits/c6491dc09853309a9080350460cd744cfce56639

**Comment by develoQ** [comment]
It looks like the translation information is now set in the repository.

Should I point out Japanese translations through Issues?
Can I create a PR directly?

**Comment by N3TC4T** [comment]
Thanks @develoQ Yes we moved the translations to the repo, for sure you can always open pull request (in [develop branch](https://github.com/XRPL-Labs/XUMM-App/tree/develop)) 🙏

**Comment by develoQ** [comment]
Okay! Thanks!
