### ISSUE TITLE
[Bug] Invalid Owner Reserve

### ISSUE THREAD

**Issue by develoQ** [XRPL-Labs/XUMM-Issue-Tracker#429]
**Describe the bug**
If there are two or fewer objects subject to Owner Reserve, the Owner Reserve required by the RippleState object is 0 XRP.

https://xrpl.org/trust-lines-and-issuing.html#free-trust-lines

**To Reproduce**
Set up two trust lines from accounts whose balances match the Base Reserve

https://testnet.xrpl.org/accounts/rJzJwydbzVLqJSgLW99T7auNo7Wuy8aNgu

**Expected behavior**
In the following screenshots, Total Reserved here should be 10XRP, and the Owner Reserve of the Token should be 0 XRP.

**Screenshots**
![image](https://user-images.githubusercontent.com/69445828/219328018-93af10cf-6b52-41f5-ba3a-2a4ac42e4671.png)

### Environment

* XUMM version: 2.3.1.2

**Comment by WietseWind** [comment]
Thanks for reporting this, but it's actually not a bug.

The XRPL _does_ enforce the reserve on the first two trust lines. They are not "free". They reserve two XRP, it's just that the XRPL doesn't enforce the first two reserved when spending.

So the reserve breakdown is correct, and your wallet technically has a negative spendable balance. The XRPL just doesn't enforce it.

You will notice when you deposit to that wallet: the first XRPs deposited will be used to fill the negative reserve balance.

So: example:

- Account balance: 11 XRP
- Account reserve: 10 XRP reserve
- Two trust lines: 2x 2 = 4 XRP reserve

Balance: 11 XRP, reserved: (10+4=) 14 XRP.

Spendable balance: 11-14 = -3 XRP

Now if you deposit 5 XRP to this wallet, the first three will satisfy the required reserve for the two Trust Lines, so your spendable balance will be **5-3 = 2 XRP**.

The above example proves that the reserve __is not free__, it's reserved, it's just not enforced.

**Comment by develoQ** [comment]
I checked at hand and it certainly looks like it! Thank you!

However, I understand that technically it can be a negative balance, but I think many Xumm users find that difficult to understand.
I think that when the actual value of Available for spending is negative, it should show 0, or show why it is negative.

A number of people in the Japanese community also raised questions about the negative value notation.

**Comment by N3TC4T** [comment]
We actually tried showing the zero instead of negative value but then it will confuse people more as for example they have -3 balance and we show it as zero and then they transfer 5 XRP to their account but their balance shows only 2 XRP and they will question where is the other 3 XRP.
