### ISSUE TITLE
[Bug] Sorting of xApp panel is stuck

### ISSUE THREAD

**Issue by whywefight** [XRPL-Labs/XUMM-Issue-Tracker#431]
**Describe the bug**
It seems to be device specific but since the last time using the vanity gen, the app sticks as the first one in the list.

**To Reproduce**
I was unable to reproduce this with any other xApp/device.

**Expected behavior**
Afaik, the app I used last should be first in the list.

**Screenshots**
[If applicable, add screenshots or a video to help explain your problem.]

https://user-images.githubusercontent.com/30388756/221338266-83c5a3ac-bf26-4cd0-8907-a1d670c22329.mp4

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 2.4.0.3166139 (the issue existed before the update)

What device are you running XUMM on?

* Manufacturer: Samsung
* Model: Galaxy Note20 Ultra
* OS version: Android 13
* Platforms
  * [ ] iOS
  * [x] Android

### Additional context
Attach crash logs if available. Please ensure that these files do not contain any personal information.

**Comment by WietseWind** [comment]
It should indeed show the last xApp opened. I'm running the same version here and that's how it behaves for me.

Can you share your device identifier (Settings - Advanced) so I can check?

**Comment by whywefight** [comment]
Here we go;

9DDC038E-2AE9-4F73-AAEB-804E0C3DEEF2

**Comment by WietseWind** [comment]
I found the cause;
<img width="431" alt="image" src="https://user-images.githubusercontent.com/4756161/221441979-d95bf233-8c3e-4133-9750-51994c996d48.png">

<img width="1787" alt="image" src="https://user-images.githubusercontent.com/4756161/221441974-49cbab59-aaf6-4456-8ac8-608c6e8cc581.png">

So **if** you opened an xApp and it is on our featured list, it'll be ordered above the most opens. As designed. 

I will think about a way to tweak this query to make the featured xApp drop out of the list sooner, based on last opened time for example.

Thanks!

**Comment by WietseWind** [comment]
OK, changed to this:
```
        UNIX_TIMESTAMP(DATE_FORMAT(max(Q1.last_open), '%Y-%m-%d')) DESC,
        a.application_xapp_featured DESC,
        SUM(Q1.opens) DESC
```
...

This will only do this on the same day. So same day both last opened? Featured one comes first. The next day, if the non-featured app is opened again, it'll come before the featured one.

**Comment by whywefight** [comment]
I have a couple ones I always use. It would be cool if I could pin these 4 to row one, and the rest is based on "last used".

**Comment by WietseWind** [comment]
> I have a couple ones I always use. It would be cool if I could pin these 4 to row one, and the rest is based on "last used".

Agree, that's coming as part of https://github.com/XRPL-Labs/XUMM-Issue-Tracker/issues/430#issuecomment-1439319060 :)



> EDIT: Vanity Address is now unstuck 

Great!
