### ISSUE TITLE
[Improvement] DestinationTag not fully visible in German

### ISSUE THREAD

**Issue by rsteimen** [XRPL-Labs/XUMM-Issue-Tracker#432]
**The Problem**
Due longer texts in German, a destinationTag is maybe not fully visible during payment confirmation. Attached screenshot misses 1 digit. Screenshot captured on Sony Xperia Z1 Compact.

![Screenshot_20230309_114215](https://user-images.githubusercontent.com/58305632/224002679-1af83977-1a9e-4ae8-81d7-470fe9d46028.png)

**Comment by WietseWind** [comment]
Thanks! Will fix, force to multi-line or another solution to be suggested by @N3TC4T  :)

**Comment by N3TC4T** [comment]
Thanks fixed in https://github.com/XRPL-Labs/XUMM-App/pull/82/commits/5c6f91ba29b06e545c1c186b3c813942500097ec

<img src="https://user-images.githubusercontent.com/6250203/226632665-128a755d-0bd8-4226-8537-4aab5c75773d.png" height="300px" />
