### ISSUE TITLE
[Spelling mistake] 'sop' in dutch needs to be 'op'

### ISSUE THREAD

**Issue by KoenPaas** [XRPL-Labs/XUMM-Issue-Tracker#433]
A spelling mistake on the dutch language:

sop -> op
Remove the 's'

![image](https://user-images.githubusercontent.com/36813373/225562754-a319360c-74fa-4bac-b589-c684ee892324.png)

**Comment by N3TC4T** [comment]
Fixed in https://github.com/XRPL-Labs/XUMM-App/pull/89/commits/8088e62f40e0b1171b1f9c8508bf9ca64afe8e73
