### ISSUE TITLE
Error code 603

### ISSUE THREAD

**Issue by stingr4y78** [XRPL-Labs/XUMM-Issue-Tracker#437]
Error: Error code 603, see XUMM Dev Console, reference: 86ff8564-d3e9-41ba-be8c-dee489b6621d**Describe the bug**

**To Reproduce**
JS code/////////////////////////////////////////////
const {XummSdk} = require('xumm-sdk');
const Sdk = new XummSdk('9c8aaee2-8730-4295-84b9-16c999a952a9', 'be6591d8-675e-4736-8777-64e78dc84388');
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080 }, () => {
  console.log('WebSocket server started');
});
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
wss.on('connection', (ws) => {
  console.log('New client connected');

  ws.on('message', (message) => {
    console.log(`Received message: ${message}`);
    const paymentDetails = JSON.parse(message);
    //console.log(typeof paymentDetails.destination)
   // console.log(paymentDetails.amount)
   // console.log(paymentDetails.memo)

    main(ws, paymentDetails);

  });

  ws.on('close', () => {
    console.log('Client disconnected');
  });
});
///////////////////////////////////////////////////////////////////////////////////////////////////
async function main(ws, paymentDetails) 
{
  console.log(paymentDetails.destination)
  const appInfo = await Sdk.ping()
  console.log(appInfo.application.name)

  const request = {
    "TransactionType": "Payment",
    "Destination": paymentDetails.destination,
    "Amount": paymentDetails.amount,
    "Memos": [
      {
        "Memo": {
          "MemoData": paymentDetails.memo
        }
      }
    ],
    "expire": 300
  }

  const subscription = await Sdk.payload.createAndSubscribe(request, event => {
    console.log('New payload event:', event.data)

    if (event.data.signed === true) {
      console.log('Woohoo! The sign request was signed :)')
      ws.send('The sign request was signed :)')
      return event.data
    }

    if (event.data.signed === false) {
      console.log('The sign request was rejected :(')
      ws.send('The sign request was rejected :(')
      return false
    }
  })

  console.log(subscription)

  var sub=subscription

 // ws.send(sub);
}
////////////////////////////////////////////////////
/////////////////////////////////////////////////////HTML code
<!DOCTYPE html>
<link rel="stylesheet" href="style.css">
<html>
<head>
  <meta charset="utf-8">
  <title>Send XRP Address</title>
</head>
<body>
  <h1>Enter payment details to send XRP</h1>

  <label for="destinationInput">Destination:</label>
  <input type="text" id="destinationInput"><br><br>

  <label for="amountInput">Amount:</label>
  <input type="text" id="amountInput"><br><br>

  <label for="memoInput">Memo:</label>
  <input type="text" id="memoInput"><br><br>

  <button onclick="sendMessage()">Send Payment Request</button>

  <div id="image-container"></div>

  <p id="response"></p>

  <script>
    const socket = new WebSocket("ws://localhost:8080");

    socket.onmessage = function(event) {
      const imageLink = event.data

      // Open new window to display the image
      const newWindow = window.open(imageLink, '_blank', 'height=600,width=800')
      if (!newWindow || newWindow.closed || typeof newWindow.closed == 'undefined') {
        alert('Popup blocked. Please allow popups to open the image.')
      }
    };

    function sendMessage() {
      const destination = document.getElementById("destinationInput").value;
      const amount = document.getElementById("amountInput").value;
      const memo = document.getElementById("memoInput").value;

      const paymentDetails = {
        "destination": destination,
        "amount": amount,
        "memo": memo
      };

      socket.send(JSON.stringify(paymentDetails));
    }
  </script>
</body>
</html>
///////////////////////////////////////////////////
**Expected behavior**
After running the node.js file, when I try to connect the HTML file to the node instance using websockets, it crashes with the "603" error. works ok If I hard code the payment, amount etc info, just when I try and send the values from the front end do I get a problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/24524822/227627717-b5a4340f-f431-4828-ab57-e22afd222133.png)

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* using xumm-sdk in visual studio

What device are you running XUMM on?

Windows 10

### Additional context
Attach crash logs if available. Please ensure that these files do not contain any personal information.

**Comment by WietseWind** [comment]
# Please visit the Xumm Developer Console and click the button to re-generate your secret: your information above contains your API key + secret.
