### ISSUE TITLE
[Bug] Translation error causing template string to be rendered.

### ISSUE THREAD

**Issue by antondalgren** [XRPL-Labs/XUMM-Issue-Tracker#441]
**Describe the bug**
The exchange rate title contains a template string.

**To Reproduce**
Use Swedish as language, haven't tried if it's isolated to Swedish or not.
Try to change 3 XRP to SOLO, on the confirm screen the issue will appear.

**Screenshots**
![xumm transaltion bug](https://github.com/XRPL-Labs/XUMM-Issue-Tracker/assets/9164583/c02b6e26-a61d-4b02-8f80-1e29ff33ca8d)

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 2.5.0

What device are you running XUMM on?

* Manufacturer: Oneplus
* OS version: 11
* Platforms
  * [ ] iOS
  * [x] Android

**Comment by N3TC4T** [comment]
Fixed in https://github.com/XRPL-Labs/XUMM-App/pull/89/commits/c6491dc09853309a9080350460cd744cfce56639
