### ISSUE TITLE
[Bug] User stuck on signing platform website when payload has expired

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#50]
**Describe the bug**
When redirecting a user to the next.always URL of the payload response (as example on desktop) a QR code is shown. If the QR code is expired, the website (https://xumm.app/sign/:payloadId) does not redirect back to the original application and the user is "stuck" in this screen.

When scanning the expired QR code, there will be a proper error message in the app but the website says "Waiting for you to resolve (accept / deny) the "Payment" request in XUMM app."
But that is not possible because the payload has expired before it was opened/scanned.

**To Reproduce**
1. Create a payload with expiry time of 1 minute
2. redirect the user to the 'next.always' URL of the payload submit response
3. wait more than one minute to let the payload expire

**Expected behavior**
It would be cool if the website (https://xumm.app/sign/:payloadId) shows an error/warning when the 
payload has expired and offers the possibility to redirect to the original page like:
"The payload has expired and cannot be signed anymore. Click *here* to return to the previous website"

### Environment

(not so important here. Not app bug :-) )

**Comment by WietseWind** [comment]
Thanks @nixer89 - Fixing that straight away :)

**Comment by WietseWind** [comment]
In case of an already opened payload that expired while waiting QR scanning:
![image](https://user-images.githubusercontent.com/4756161/77811832-73036480-709d-11ea-8b70-ebfe3fa2dcdd.png)

In case of a link to the Sign URL after expiration:
![image](https://user-images.githubusercontent.com/4756161/77809722-3e89ab80-7091-11ea-8b5b-0098b54ff28d.png)
