### ISSUE TITLE
[Suggestion] Spendable XRP amount shows negative value

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#53]
**Describe the <suggestion>**
When the account reserve is bigger than the account balance, the spendable XRP balance shows a negative value.

**To Reproduce**
1. Having an account with 21 XRP and account reserve of 20 XRP
2. Add a new trustline which adds 5 XRP to the accounts reserve
3. spendable balance shows -4 (in send screen and in exchange screen for an IOU)

**Expected behavior**
Spendable balance should not be negative and should show 0 instead, see comment by @WietseWind below.

**Screenshots**
![5073480B-D185-40D4-B5D5-0534678F96CF](https://user-images.githubusercontent.com/25486793/77701946-ad92d180-6fb7-11ea-9e5d-0cfe1a0f4860.png)
![78DBD915-87C7-4F50-9F94-CB9E55DBE61C](https://user-images.githubusercontent.com/25486793/77701949-ae2b6800-6fb7-11ea-8b69-ef83620be667.png)

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 0.1.6.1

What device are you running XUMM on?

* Manufacturer: Apple
* Model: iPhone SE
* OS version: 13.1
* Platforms
  * [x] iOS
  * [ ] Android

### Additional context
Attach crash logs if available. Please ensure that these files do not contain any personal information.

**Comment by WietseWind** [comment]
@nixer89 The spendable balance for a 21XRP account with one Trust Line is in fact negative, you can't spend anything.

Do I understand it correctly that you suggest to round (cap, limit min) spendable on 0, to prevent user confusion?

**Comment by nixer89** [comment]
Yes, in technical terms it's a negative balance but this usage is not common outside techies and accounting people.

"how much for can you spend? "
"let me check... Erm, negative 9" 😅

So yes, I would suggest to rather show it as "0" than an negative value, for the sake of user friendliness 🙂

**Comment by WietseWind** [comment]
Yes, that makes sense. Not really a bug though, I'm renaming to `Improvement` and I'll add it to the V1 release board 👍 
Thanks, good suggestion!
