### ISSUE TITLE
[Change] Always send connected XRPL net to `dispatched.nodetype` on payload resolve

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#54]
When resolving a payload (either rejecting or signing), **no matter if the app had to submit or not**, post the `dispatched.nodetype` property (string) to the payload resolve API too, containing either live/test/ or livenet/testnet (or mainnet/..., however they are called internally).

So:
- Even if rejecting
- Even if `submit` = false
- Even for `SignIn` pseudo tx type

Reason: this way the XUMM 3rd party app knows where to verify the TX. We removed it earlier on when users could still add custom nodes (as it was unreliable, as the node didn't have to be on the net the user selected) but now with fixed node list, this is reliable and a good addition.

**Comment by WietseWind** [comment]
This is now an empty string?

**Comment by N3TC4T** [comment]
<img width="494" alt="Screenshot 2020-04-28 at 13 49 54" src="https://user-images.githubusercontent.com/6250203/80483922-2e4a4200-8957-11ea-84f5-1b5bcf183e89.png">
<img width="498" alt="Screenshot 2020-04-28 at 13 48 43" src="https://user-images.githubusercontent.com/6250203/80483931-30140580-8957-11ea-90ef-e7c09fd04ee4.png">

Not really I tested and it will patch correctly

**Comment by niraj-khatiwada** [comment]
The dispatched_node type is always empty even in mainnet:
![image](https://user-images.githubusercontent.com/51436631/172913211-464024e4-f172-4b96-a8c4-512b09063c83.png)

The getTransaction method from sdk only returns node but not nodetype.
![image](https://user-images.githubusercontent.com/51436631/172913311-2de7b11a-ce49-43a9-8f6d-f89cdb1218e3.png)

How do we know that the user signed from Mainnet/Devnet/Testnet ?

**Comment by WietseWind** [comment]
@niraj-khatiwada I looked up the payload you are referring to. That's a SignIn payload. SignIn payloads aren't real transactions as in: they are never sent to the XRP Ledger, they are just there to verify your signature.

This means SignIn payloads are never submitted to the XRPL (the XRPL would reject the transaction as it doesn't know a SignIn transaction, that's a Xumm feature), and because they are not submitted:
- You don't get a node (it was never sent)

**Comment by niraj-khatiwada** [comment]
> @niraj-khatiwada I looked up the payload you are referring to. That's a SignIn payload. SignIn payloads aren't real transactions as in: they are never sent to the XRP Ledger, they are just there to verify your signature.
> 
> This means SignIn payloads are never submitted to the XRPL (the XRPL would reject the transaction as it doesn't know a SignIn transaction, that's a Xumm feature), and because they are not submitted:
> 
> * You don't get a node (it was never sent)
> * You can't find them on the blockchain
> 
> (Mentioning @N3TC4T and @DominiqueBlomsma for reference)

Okay understood. So what's the strategy for allowing signing from main net only? Platform  like `Sologenic` detects the test and dev accounts and throws not activated error message as shown below. I have a exact use case. Does package have `xrpl-txdata` has any method for it?
![image](https://user-images.githubusercontent.com/51436631/172938664-29d096b9-40c8-4ed8-98a1-e66a05b2bbd0.png)

**Comment by WietseWind** [comment]
Hi @niraj-khatiwada, may I invite you to post questions / developer questions / issues (so: non bugs, non user stories) on our developer questions board? https://xumm.readme.io/discuss - this keeps our existing tickets & issues clean.

**Comment by niraj-khatiwada** [comment]
> Hi @niraj-khatiwada, may I invite you to post questions / developer questions / issues (so: non bugs, non user stories) on our developer questions board? https://xumm.readme.io/discuss - this keeps our existing tickets & issues clean.
> 
> Please note that if your question is regarding the network & the SignIn payload: a SignIn is just to prove account keypair possession, the net is completely irrelevant here. If this question is about actual non-SignIn transactions, I'll gladly answer at our Developer Questions dashboard. That way we keep the issues clean & gather all the right info in once place: in our developer documentation.

Yes please. I would love to. I have so many questions...
