### ISSUE TITLE
[Bug] Doesn't jump to new line (or header, "B") on importing full access secret numbers

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#69]
Not jumping to line B of secret type numbers when importing existing full access account!

https://app.intercom.com/a/apps/nq9rb5du/inbox/inbox/all/conversations/26404795146

**Comment by WietseWind** [comment]
Detail: user didn't notice the numbers turning red, or didn't understand red was not OK. We should add a message besides making it red if the range is not OK.

https://nw3aayy.dlvr.cloud/VID-20200330-WA0000.mp4

**Comment by WietseWind** [comment]
![Uploading image.png…]()

**Comment by WietseWind** [comment]
https://app.intercom.com/a/apps/nq9rb5du/inbox/inbox/all/conversations/26420842262

**Comment by N3TC4T** [comment]
this is reported before and already fixed,
