### ISSUE TITLE
[Bug] Long payment loading, no message, just returns home

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#71]
https://twitter.com/pucksterpete/status/1244682386320867331 Destination account was activated:
https://bithomp.com/explorer/rEpNSXMaEhCC1Qozsb6jY2vh5LGVwSgfBi

No matter the reason or error: it should always show a message and the user should always know for sure if it worked or not, and why.

Debug log sent (by mail to me to @N3TC4T )

**Comment by Pucksterpete** [comment]
Info for you guys, I cleared the data from the app and started over, this time I selected 'standard' for account creation, sending out payments working fine, no long payment loading.
Yesterday with first install of the app I selected 2nd option for acct creation, having to enter passphrase to send payments, that is where I was having problems, which still occurs today if 2nd option is selected on acct creation.  Hope this helps narrow the problem.
