### ISSUE TITLE
[Explain] Show message in adding other currency modal

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#75]
Report:
https://twitter.com/JonJimbo2/status/1244632127259447302

Answer (and fix)
https://twitter.com/WietseWind/status/1244712458796793856

TLDR: show that adding a currency reserves adds 5 xrp to the reserve, will be available again when you remove the currency again in the future.

**Comment by N3TC4T** [comment]
`Adding a currency will increase your account reserve with 5 XRP`
