### ISSUE TITLE
[Improvement] Read only account with Regular Key & Regular Key present: becomes read/write

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#80]
When a user imported a rekeyed account as read only (makes sense, I can understand this thought process) and then the matching regular key is imported, turn the read only account in read/write (not completely, but allow it to be used for transactions, as we can sign for it)

## NOTE on Read Only + regular key
If a Read Only account is imported and the regular key is imported as read/write, the regular key should ALSO be used if the master key is NOT disabled, since the master key is effectively disabled (from the XUMM perspective) because the account is read only (so private key is unknown anyway)
(Thanks @jon_nilsen for this addition)

**Comment by WietseWind** [comment]
https://twitter.com/WietseWind/status/1244765199879622656

**Comment by RareData** [comment]
Needed before we can integrate Xumm with the XRP Toolkit. Would appreciate a speedy implementation of this functionality.

**Comment by jonaagenilsen** [comment]
rGzeoSb5fDPyMAP5zeNGvF1KZLZfJcLuKg is already added in XUMM v0.4.1.3146129. 

rKmBmEE7QsH9mRL3SKhYJYEgmGGFRvN8c5 has wallet above set as Regular Key and Master key is not disabled. When adding this wallet to XUMM (by scanning QR on Bithomp.com) I still get a "Account already exists!"

**Comment by jonaagenilsen** [comment]
So cool! Finally got to add my Validator wallet which has regular key set and masterkey _not_ disabled. Horay!
