### ISSUE TITLE
[Improvement] UI button overlap

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#89]
**Describe the bug**
https://twitter.com/msherm044/status/1244651599978467328

**Comment by N3TC4T** [comment]
It's not a bug, this is a overlay on top of review transactions screen, when you scan a sign request and you don't have any account to sign with this screen will shown to the user

**Comment by WietseWind** [comment]
I think the user meant the button over the rectangle. Not a pressing issue.

**Comment by N3TC4T** [comment]
https://github.com/XRPL-Labs/XUMM-App/pull/20/commits/4402057fe286bcc3229c5e627b9fb6dab9494898
