### ISSUE TITLE
[Workaround] If URL with TOS can't be fetched

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#91]
At the app launch, when the TOS URL can't be fetched:
```
Error Loading Page Domain: NSURLErrorDomain Error Code: -1001 Description: The request timed out. 
```

... I think we should show a clearer error message, explaining the Terms of Service URL couln't be retrieved. Try again later, or ifyou are on a limited connection: try with a VPN. Or something like that.

**Comment by N3TC4T** [comment]
https://github.com/XRPL-Labs/XUMM-App/pull/89/commits/46e039319ee66f33275e733e19050926f04b04d9

<img src="https://github.com/XRPL-Labs/XUMM-Issue-Tracker/assets/6250203/91e418aa-783e-4fef-a345-0ad640c3aac7"  width="200px"/>
