### ISSUE TITLE
[Interface] Small screen: buttons over text

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#92]
https://twitter.com/CarneWillie/status/1244875278620360704

We need to shorten those descriptions, I guess. And maybe some less top/bottom padding for those boxes if the screen height is limited.

**Comment by WietseWind** [comment]
And maybe remove the heads, just:
>"Sign with PIN / FaceID / Finger"
Ideal for daily spending. Sign by entering a PIN, scanning your finger or face,

>"Sign with a passphrase"
Better for holding and savings, not as user friendly for quick spending.

**Comment by WietseWind** [comment]
iPhone se(5)

**Comment by N3TC4T** [comment]
https://github.com/XRPL-Labs/XUMM-App/pull/20/commits/8267f037bb41ecb073522d4cfea8f7767e779206
