### ISSUE TITLE
[Improvement] Add warning message on import mnemonic screen

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#93]
On top of the import mnemonic page:

If you use your mnemonic account for holding larger amounts of XRP, you may want to create a new account in XUMM, to keep your mnemonic account offline. You can import your mnemonic account as a Read Only [button, import read only] into XUMM (just to check balance and transaction history), or continue by entering the mnemonic below.

**Comment by mp3yeur** [comment]
Hi team ! Thanks for your hardwork, app is great !

Im not sure my question is fully undertood. It's not easy for me to write natively in english sorry for that. Im french native.

1) Please activate mnemonic derivative passphrase in Xumm (for common family current account, this family use a same mnemonic 12/24 word shared between each person of family with diferents passphrases for each person, not used for store big amount of currencies like cold wallet/vault, hot wallet wil be only used for shopping and little daily transactions) 

Example :

- Familly account (same mnemonic 12/24 words for all family only used for daily transaction, not storage of value/vault)
   |
  +-- Dad 
   |     (passphrase : FT2HHUHU@GFYFRrezr34564-TEST)
  +-- Mom
   |    (passphrase : ezdg56gFRDSdzdf@121)
  +-- Daughter
   |    (passphrase : FZSGZZGYTezdezd4317@@@23)
  +-- Son..ect........................................................

That include mnemonic 12/24 word will be stay safe on all phones, under control with no unsecure applications installed on it, with limited permission for each user, it's my job, im administrator in real life. With separate cold wallet mnemonic 24 word used for cold wallet for largers accounts (not added in xumm).

2) A warning message is displayed when derivative mnemonic passphrase is used to warn user to don't use mnemonic cold wallet mnemonic with larger amout of money in xumm.

Thanks a lot to try to implement this feature if possible.

**Comment by WietseWind** [comment]
Ah, I didn't understand the "25th word" (passphrase). I'll move that to another issue, let's keep one issue per issue ;)

**Comment by WietseWind** [comment]
Text suggested:
```
If you import your mnemonic account and your account holds your savings (larger amounts of XRP or other tokens) please consider creating a new account in XUMM to keep your mnemonic account offline. 

[Read more in the FAQ] » https://support.xumm.app/en/articles/3852597-how-does-xumm-security-compare-to-a-hardware-wallet
```

- Import Read Only account (only check balance and transactions)

- Continue importing mnemonic account

**Comment by mp3yeur** [comment]
Perfect, i will update fr locale file tomorrow, i will verify other news
changes on this file to translate news features.

Thanks Wietse!


---
Cordialement,
Kind regards,

LESORT-PAJOT Sébastien
e-mail : sebastien@lesort-pajot.com

Mobile : +33 (0)7 60 07 11 57  (ligne totalement restreinte)

"Les perdants arrêtent quand ils échouent, les gagnants échouent jusqu'à ce
qu'ils réussissent..." Robert Kiyosaki

Le jeu. 2 avr. 2020 à 23:36, Wietse Wind <notifications@github.com> a
écrit :
