### ISSUE TITLE
[Investigate] Some clients with many simultaneous websocket connections

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#94]
@N3TC4T + @WietseWind will investigate later on. This is a reminder.

**Comment by WietseWind** [comment]
Random thought: see if it isn't my ws client if temp disconnected, eg. not killing the old connection before starting a new one.

**Comment by N3TC4T** [comment]
Can you check the app version by looking at origin ?

**Comment by WietseWind** [comment]
Yes, it's visible @ https://www.xrptipbot.com/rippled
Mostly:
```https://xumm.app/#android/0.2.4.3145932 ```

**Comment by WietseWind** [comment]
Long fixed
