### ISSUE TITLE
[Bug] Duplicate search results » Actually: clearer source of search results (lookup), see comment Wietse

### ISSUE THREAD

**Issue by martijnjanssen** [XRPL-Labs/XUMM-Issue-Tracker#95]
**Describe the bug**
When trying to search myself when making a payment, after typing in the name of my xrplns account, I get two results.

**To Reproduce**
1. Go to 'Send XRP'
2. Add some amount
3. Click 'next'
4. Enter name 'martijn'
5. See 2 addresses, 'rq7...' being the correct one from [xrplns.com/users/martijn](https://xrplns.com/users/martijn)

**Expected behavior**
I think there is only supposed to be one result here.

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 0.2.4.3145932

**Comment by martijnjanssen** [comment]
After trying something else, typing "Martijn" results in the xrlpns account having a result with uppercase, but the "martijn" account was also still in the results.

**Comment by WietseWind** [comment]
Hey! Thanks so much for testing @martijnjanssen 

The reason is there are actually two results from different sources:
```
{
  "input": "martijn",
  "live": true,
  "cached": 1585652072,
  "explicitTests": {
    "emailAddress": false,
    "xrplAccount": false
  },
  "matches": [
    {
      "source": "bithomp.com",
      "network": null,
      "alias": "martijn",
      "account": "rnq3cjHDkmQhFgscDqWqD5ZRPs9iZ5nqUd",
      "tag": null,
      "description": ""
    },
    {
      "source": "xrplns",
      "network": "local",
      "alias": "martijn",
      "account": "rq7LQxtH6iU92fkav8yVroYJZuCSJiutv",
      "tag": null,
      "description": "Xumm"
    }
  ]
}
```

(Raw output from our lookup backend). 

We will make improvements to make it more clear where the result is coming from, and we'll add verified XUMM profiles later on.

**Comment by martijnjanssen** [comment]
Okay, cool! Thanks for having a look this quickly.

**Comment by N3TC4T** [comment]
Lets continue here

https://github.com/XRPL-Labs/XUMM-Issue-Tracker/issues/25
