### ISSUE TITLE
[Feature] Allow 13th/25th... passphrase word for mnemonic import

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#96]
As originally reported in https://github.com/XRPL-Labs/XUMM-Issue-Tracker/issues/93

>Im not sure my question is fully undertood. It's not easy for me to write natively in english sorry for that. Im french native.

> 1) Please activate mnemonic derivative passphrase in Xumm (for common family current account, this family use a same mnemonic 12/24 word shared between each person of family with diferents passphrases for each person, not used for store big amount of currencies like cold wallet/vault, hot wallet wil be only used for shopping and little daily transactions) 

>Example :

```
- Familly account (same mnemonic 12/24 words for all family only used for daily transaction, not storage of value/vault)
   |
  +-- Dad 
   |     (passphrase : FT2HHUHU@GFYFRrezr34564-TEST)
  +-- Mom
   |    (passphrase : ezdg56gFRDSdzdf@121)
  +-- Daughter
   |    (passphrase : FZSGZZGYTezdezd4317@@@23)
  +-- Son..ect........................................................
```

> That include mnemonic 12/24 word will be stay safe on all phones, under control with no unsecure applications installed on it, with limited permission for each user, it's my job, im administrator in real life. With separate cold wallet mnemonic 24 word used for cold wallet for largers accounts (not added in xumm).

**Comment by WietseWind** [comment]
The way to implement this (imo):

__After__ entering all the words (wordlist) at importing mnemonic:

Checkbox/switch: "Use extra Mnemonic Passphrase word"
If selected/on, show another input under that, where people can enter anything, and then (xrpl-accountlib) send that to the `passphrase` option:
![image](https://user-images.githubusercontent.com/4756161/78020821-6ce9de00-7352-11ea-847b-077b080d1bbc.png)

https://github.com/WietseWind/xrpl-accountlib

**Comment by WietseWind** [comment]
... Thanks @mp3yeur :)

**Comment by mp3yeur** [comment]
Yes it's that (25th word). Thanks a lot Wietse! 

In doubt, i have done another test in Xumm and today im sure that 25th word is not actually enabled, my public xrp address is the same with and without activate xumm passphrase. Then, passphrase in Xumm is not a 25th word.

If possible, please enable it.

**Comment by WietseWind** [comment]
We will :)
