### ISSUE TITLE
[Bug] Adding address in contacts - „paste“ button has white color

### ISSUE THREAD

**Issue by xrpbird** [XRPL-Labs/XUMM-Issue-Tracker#99]
![image](https://user-images.githubusercontent.com/4756161/78104437-80975200-73ef-11ea-9a9b-62fe5e93b55d.png)

**Comment by WietseWind** [comment]
@xrpbird Thank you so much :) We'll be fixing this by adding a nice Paste button there.
@thisistriss

**Comment by WietseWind** [comment]
@xrpbird Do you perhaps have your phone in dark mode? (To help us understand the conditions)

**Comment by WietseWind** [comment]
@N3TC4T Superseded by #101

**Comment by xrpbird** [comment]
Yes, Dark Mode was enabled.
I couldn‘t reproduce it in Light mode.
Sorry for adding only a screenshot ;)

xrbpird

**Comment by WietseWind** [comment]
Awesome, thanks. Then this will be fixed when we add Dark mode:
https://xrpl-labs.canny.io/xumm/p/add-dark-mode-theme

In the mean time we will make it easier to paste with #101 and #86
